import { Subject, Module, AcademicResource, YouTubeResource, FlashcardDeck, MermaidDiagram } from './types';

export const INITIAL_SUBJECTS: Subject[] = [
  // --- SEMESTER I ---
  {
    id: 'sub-math1',
    semester: 1,
    code: '316U06C101',
    name: 'Applied Mathematics – I',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 4,
    theoryCredits: 3,
    tutorialCredits: 1,
    practicalCredits: 0,
    hasLab: false,
    description: 'Rank of matrix, linear systems, partial differentiation, Maxima-Minima, Jacobians, Euler theorem, ordinary differential equations, complex numbers, and hyperbolic functions.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
    iconName: 'Calculator',
  },
  {
    id: 'sub-phy',
    semester: 1,
    code: '316U06C102',
    name: 'Engineering Physics',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 2,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Thin film interference, Newton’s rings, diffraction grating, lasers, optical fibers, quantum mechanics wavefunctions, semiconductors, and electromagnetism.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=600&auto=format&fit=crop&q=80',
    iconName: 'Atom',
  },
  {
    id: 'sub-chem',
    semester: 1,
    code: '316U06C103',
    name: 'Engineering Chemistry',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 2,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Industrial water hardness & treatment (BOD/COD), 12 principles of green chemistry, synthetic organic name reactions, rearrangements, electrochemistry, and corrosion control.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    iconName: 'FlaskConical',
  },
  {
    id: 'sub-bee',
    semester: 1,
    code: '316U06C104',
    name: 'Basic Electrical Engineering',
    category: 'ES',
    scheme: 'REV_2025',
    credits: 2,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'DC network theorems (Thevenin, Norton, Superposition, Max Power), 1-phase AC RLC circuits, resonance, 3-phase star/delta power, transformers, DC motors, and induction motors.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    iconName: 'Zap',
  },
  {
    id: 'sub-ed',
    semester: 1,
    code: '316U06C105',
    name: 'Engineering Drawing',
    category: 'ES',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 2,
    tutorialCredits: 1,
    practicalCredits: 0,
    hasLab: false,
    description: 'First angle orthographic projections, full sectional views, projection of points, lines, planes, regular solids, lateral surface development, and isometric drawings.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    iconName: 'Compass',
  },
  {
    id: 'sub-bio',
    semester: 1,
    code: '316U06C106',
    name: 'Biology for Engineers',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 2,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Biomolecules, enzyme kinetics, cell biology, DNA/RNA, bioinformatics, bioprocess fermentors, biosensors, biomedical instrumentation (ECG/EEG/MRI), systems biology, and biomechanics.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&auto=format&fit=crop&q=80',
    iconName: 'Dna',
  },
  {
    id: 'sub-spm',
    semester: 1,
    code: '316U06C107',
    name: 'Structured Programming Methodology',
    category: 'ES',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 1,
    hasLab: true,
    description: 'Problem solving algorithms, control flow constructs, 1D/2D arrays, string operations, modular functions, recursion, structures, unions, pointers, and memory handling.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    iconName: 'Code',
  },

  // --- SEMESTER II ---
  {
    id: 'sub-math2',
    semester: 2,
    code: '316U06C201',
    name: 'Applied Mathematics – II',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 4,
    theoryCredits: 3,
    tutorialCredits: 1,
    practicalCredits: 0,
    hasLab: false,
    description: 'First order exact differential equations, higher order linear ODEs, beta & gamma functions, DUIS, double integrals, area/volume computation, triple integrals, and vector calculus.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    iconName: 'Calculator',
  },
  {
    id: 'sub-sps',
    semester: 2,
    code: '316U06C202',
    name: 'Program-Specific Science Course',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 3,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Specialized scientific fundamentals, solid state physics, computational chemical modeling, smart materials, nanotechnology, and advanced sensor principles.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop&q=80',
    iconName: 'Microscope',
  },
  {
    id: 'sub-spc',
    semester: 2,
    code: '316U06C203',
    name: 'Program-Specific Core Course',
    category: 'ES',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 3,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Foundational departmental engineering core principles, systems modeling, hardware/software design abstractions, and domain-specific analytical case studies.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    iconName: 'Cpu',
  },
  {
    id: 'sub-evs',
    semester: 2,
    code: '316U06C204',
    name: 'Environmental Science',
    category: 'HS',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 2,
    tutorialCredits: 1,
    practicalCredits: 0,
    hasLab: false,
    description: 'Ecosystems, natural resources, biodiversity conservation, air/water/soil pollution control, climate change, renewable energy, waste management, and environmental legislation.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80',
    iconName: 'Leaf',
  },
  {
    id: 'sub-oop',
    semester: 2,
    code: '316U06C205',
    name: 'Object-Oriented Programming Methodology',
    category: 'ES',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 1,
    hasLab: true,
    description: 'Classes, data abstraction, encapsulation, constructors/destructors, operator overloading, inheritance hierarchies, runtime polymorphism, virtual functions, templates, and STL.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    iconName: 'Code',
  },
  {
    id: 'sub-pcs',
    semester: 2,
    code: '316U06T201',
    name: 'Presentation and Communication Skills',
    category: 'HS',
    scheme: 'REV_2025',
    credits: 2,
    theoryCredits: 1,
    tutorialCredits: 1,
    practicalCredits: 0,
    hasLab: false,
    description: 'Professional business correspondence, technical report drafting, presentation design, group discussions, job interview strategies, and engineering workplace ethics.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&auto=format&fit=crop&q=80',
    iconName: 'MessageSquare',
  }
];

export const INITIAL_MODULES: Module[] = [
  // --- Applied Mathematics – I (316U06C101) ---
  {
    id: 'mod-m1-1',
    subjectId: 'sub-math1',
    moduleNumber: 1,
    title: 'Rank of Matrix and System of Equations',
    description: 'Hermitian, skew-Hermitian, unitary and orthogonal matrices. Rank using row echelon/normal forms, consistency of linear equations, Gauss-Seidel and Jacobi iteration methods.',
    topics: ['Hermitian & Unitary Matrices', 'Row Echelon & Normal Form', 'Linear Systems Consistency', 'Gauss-Seidel & Jacobi Iterations'],
    weightageMarks: 18,
  },
  {
    id: 'mod-m1-2',
    subjectId: 'sub-math1',
    moduleNumber: 2,
    title: 'Partial Differentiation and Application',
    description: 'Partial derivatives of first and higher orders, composite functions, Maxima and Minima of two independent variables, and Jacobians of two and three variables.',
    topics: ['Higher Order Partial Derivatives', 'Composite Function Differentiation', 'Maxima & Minima of 2 Variables', 'Jacobians'],
    weightageMarks: 18,
  },
  {
    id: 'mod-m1-3',
    subjectId: 'sub-math1',
    moduleNumber: 3,
    title: 'Homogeneous Functions & Euler’s Theorem',
    description: 'Euler’s theorem on homogeneous functions with two and three independent variables, and analytical deductions/corollaries.',
    topics: ['Euler’s Theorem on Homogeneous Functions', 'Corollaries & Deductions', 'Multivariable Homogeneity'],
    weightageMarks: 14,
  },
  {
    id: 'mod-m1-4',
    subjectId: 'sub-math1',
    moduleNumber: 4,
    title: 'Linear Differential Equations of First and Higher Order',
    description: 'Exact differential equations, integrating factors, higher order linear ODEs with constant coefficients, complementary functions, particular integrals, and variation of parameters.',
    topics: ['Exact Differential Equations', 'Integrating Factors', 'Higher Order Linear ODEs', 'Particular Integrals (CF & PI)', 'Variation of Parameters'],
    weightageMarks: 20,
  },
  {
    id: 'mod-m1-5',
    subjectId: 'sub-math1',
    moduleNumber: 5,
    title: 'Complex Numbers, Hyperbolic Functions & Logarithms',
    description: 'De Moivre’s theorem, powers and roots of complex numbers, circular and hyperbolic functions, inverse functions, and separation into real and imaginary parts.',
    topics: ['De Moivre’s Theorem', 'Roots of Complex Numbers', 'Hyperbolic & Inverse Hyperbolic Functions', 'Logarithm of Complex Numbers'],
    weightageMarks: 18,
  },

  // --- Engineering Physics (316U06C102) ---
  {
    id: 'mod-phy-1',
    subjectId: 'sub-phy',
    moduleNumber: 1,
    title: 'Wave Optics (Interference & Diffraction)',
    description: 'Interference in thin parallel films, wedge-shaped films, Newton’s Rings, Fraunhofer diffraction through grating, and resolving power.',
    topics: ['Thin Parallel Film Interference', 'Wedge-Shaped Films & Newton’s Rings', 'Diffraction Grating', 'Resolving Power'],
    weightageMarks: 16,
  },
  {
    id: 'mod-phy-2',
    subjectId: 'sub-phy',
    moduleNumber: 2,
    title: 'Photonics (Lasers & Optical Fibers)',
    description: 'Laser principles, Einstein coefficients, threshold condition, optical fiber total internal reflection, step index numerical aperture derivation, and fiber losses.',
    topics: ['Einstein Coefficients', 'Laser Threshold Condition', 'Optical Fiber Step Index', 'Numerical Aperture Derivation', 'Attenuation Losses'],
    weightageMarks: 16,
  },
  {
    id: 'mod-phy-3',
    subjectId: 'sub-phy',
    moduleNumber: 3,
    title: 'Quantum Mechanics – I',
    description: 'De-Broglie hypothesis, Heisenberg uncertainty principle, wavefunctions, probabilistic interpretation, and normalization condition.',
    topics: ['De-Broglie Matter Waves', 'Heisenberg Uncertainty Principle', 'Wavefunction Properties', 'Normalization Condition'],
    weightageMarks: 14,
  },
  {
    id: 'mod-phy-4',
    subjectId: 'sub-phy',
    moduleNumber: 4,
    title: 'Semiconductors & Electromagnetism',
    description: 'Intrinsic/extrinsic semiconductors, drift and diffusion currents, Fermi level position, Del operator, gradient, divergence, curl, and fundamental EM theorems.',
    topics: ['Mobility & Conductivity', 'Drift & Diffusion Current', 'Fermi-Dirac Distribution', 'Del, Gradient, Divergence, Curl'],
    weightageMarks: 16,
  },

  // --- Engineering Chemistry (316U06C103) ---
  {
    id: 'mod-ch-1',
    subjectId: 'sub-chem',
    moduleNumber: 1,
    title: 'Industrial Water Treatment & Pollution',
    description: 'Types of hardness, EDTA determination, lime-soda, zeolite, ion-exchange processes, BOD, COD, and industrial wastewater treatment.',
    topics: ['Water Hardness & EDTA Titration', 'Zeolite & Ion-Exchange Methods', 'BOD & COD Parameters', 'Industrial Effluent Treatment'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ch-2',
    subjectId: 'sub-chem',
    moduleNumber: 2,
    title: 'Green Chemistry for Sustainable Engineering',
    description: 'Twelve principles of green chemistry (Anastas & Warner), green solvents (supercritical CO2, ionic liquids), atom economy, microwave and ultrasound synthesis.',
    topics: ['Twelve Principles of Green Chemistry', 'Green Solvents & Supercritical Fluids', 'Atom Economy & Environmental Metrics', 'Microwave-Assisted Synthesis'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ch-3',
    subjectId: 'sub-chem',
    moduleNumber: 3,
    title: 'Synthetic Organic & Rearrangement Reactions',
    description: 'Aldol condensation, Baeyer-Villiger oxidation, Dakin reaction, Haloform, Sharpless epoxidation, Benzil-Benzilic, Pinacole-Pinacolone, and Fries rearrangements.',
    topics: ['Aldol & Baeyer-Villiger Reactions', 'Haloform & Sharpless Epoxidation', 'Benzilic Acid & Pinacolone Rearrangements', 'Fries Rearrangement'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ch-4',
    subjectId: 'sub-chem',
    moduleNumber: 4,
    title: 'Electrochemistry & Corrosion Fundamentals',
    description: 'Nernst equation, cell potentials, mechanisms of dry/wet corrosion, cathodic/anodic protection, corrosion inhibitors, and protective coatings.',
    topics: ['Nernst Equation & Cell Potentials', 'Corrosion Mechanisms & Types', 'Cathodic & Anodic Protection', 'Inhibitors & Protective Coatings'],
    weightageMarks: 16,
  },

  // --- Basic Electrical Engineering (316U06C104) ---
  {
    id: 'mod-bee-1',
    subjectId: 'sub-bee',
    moduleNumber: 1,
    title: 'DC Circuits & Network Theorems',
    description: 'Kirchhoff’s laws, source transformation, mesh/nodal analysis, Superposition, Thevenin’s, Norton’s, and Maximum Power Transfer theorems.',
    topics: ['Kirchhoff’s Laws & Source Transformation', 'Mesh & Nodal Analysis', 'Thevenin & Norton Theorems', 'Maximum Power Transfer'],
    weightageMarks: 20,
  },
  {
    id: 'mod-bee-2',
    subjectId: 'sub-bee',
    moduleNumber: 2,
    title: 'Single Phase AC Circuits & Resonance',
    description: 'Sinusoidal quantities, RMS, average value, phasor diagrams, RLC series/parallel circuits, power triangle (P, Q, S), power factor improvement, and resonance Q-factor.',
    topics: ['Phasor Representation & RMS Values', 'Series & Parallel RLC Circuits', 'Power Factor & Power Triangle', 'Resonance & Quality Factor'],
    weightageMarks: 18,
  },
  {
    id: 'mod-bee-3',
    subjectId: 'sub-bee',
    moduleNumber: 3,
    title: 'Three Phase AC Circuits',
    description: 'Balanced 3-phase circuits, star and delta connections, line/phase voltage-current relations, and 3-phase power measurement using two-wattmeter method.',
    topics: ['Star & Delta Connections', 'Line vs Phase Relations', 'Two-Wattmeter Power Measurement'],
    weightageMarks: 14,
  },
  {
    id: 'mod-bee-4',
    subjectId: 'sub-bee',
    moduleNumber: 4,
    title: 'Introduction to Electrical Machines',
    description: 'Single phase transformer construction, EMF equation, losses and efficiency, DC motor torque-speed characteristics, and 1-phase induction motors.',
    topics: ['Transformer Working & EMF Equation', 'Transformer Losses & Efficiency', 'DC Motor Characteristics', 'Single Phase Induction Motor'],
    weightageMarks: 14,
  },

  // --- Engineering Drawing (316U06C105) ---
  {
    id: 'mod-ed-1',
    subjectId: 'sub-ed',
    moduleNumber: 1,
    title: 'Orthographic Projections & Sectional Views',
    description: 'First angle orthographic projections of machine parts, dimensioning standards, scales, and full sectional orthographic views.',
    topics: ['First Angle Projection Principles', 'Multi-View Orthographic Layouts', 'Full Sectional Views'],
    weightageMarks: 18,
  },
  {
    id: 'mod-ed-2',
    subjectId: 'sub-ed',
    moduleNumber: 2,
    title: 'Projection of Points, Lines and Planes',
    description: 'Projections of lines inclined to both reference planes (1st quadrant), projections of regular geometric planes (triangular, square, hexagonal, circular).',
    topics: ['Lines Inclined to Both Planes', 'True Length & Apparent Angles', 'Projections of Regular Planes'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ed-3',
    subjectId: 'sub-ed',
    moduleNumber: 3,
    title: 'Projection of Solids',
    description: 'Projections of prisms, pyramids, cylinders, and cones with axis inclined to one reference plane.',
    topics: ['Prisms & Pyramids Projections', 'Cylinders & Cones Projections', 'Axis Inclination Principles'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ed-4',
    subjectId: 'sub-ed',
    moduleNumber: 4,
    title: 'Section and Lateral Development of Solids',
    description: 'Sectional views of solids cut by inclined cutting planes, and lateral surface development of prisms, cylinders, and cones.',
    topics: ['Section Planes & True Shape of Section', 'Lateral Surface Development', 'Radial Line & Parallel Line Development'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ed-5',
    subjectId: 'sub-ed',
    moduleNumber: 5,
    title: 'Isometric View & 3D Drafting',
    description: 'Isometric scale, isometric views and projections of composite machine solids.',
    topics: ['Isometric Projection vs View', 'Isometric Drafting of Machine Components'],
    weightageMarks: 14,
  },

  // --- Biology for Engineers (316U06C106) ---
  {
    id: 'mod-bio-1',
    subjectId: 'sub-bio',
    moduleNumber: 1,
    title: 'Biomolecules and Enzymes',
    description: 'Proteins, carbohydrates, lipids, nucleic acids, enzyme kinetics, cofactors, and industrial biocatalytic applications.',
    topics: ['Biomolecule Classifications', 'Enzyme Kinetics & Cofactors', 'Industrial Biocatalysis'],
    weightageMarks: 16,
  },
  {
    id: 'mod-bio-2',
    subjectId: 'sub-bio',
    moduleNumber: 2,
    title: 'Cell Biology & Bioinformatics',
    description: 'Prokaryotic/eukaryotic cells, cell cycle, DNA replication, transcription, translation, and bioinformatics sequence analysis tools.',
    topics: ['Cell Cycle & Division', 'Central Dogma of Molecular Biology', 'Bioinformatics Sequence Tools'],
    weightageMarks: 16,
  },
  {
    id: 'mod-bio-3',
    subjectId: 'sub-bio',
    moduleNumber: 3,
    title: 'Bioprocess Engineering & Fermentors',
    description: 'Fermentor vessel design, upstream/downstream processing, Monod growth kinetics, and fermentation of antibiotics/acids.',
    topics: ['Fermentor Design & Sensors', 'Upstream & Downstream Processing', 'Monod Growth Kinetics'],
    weightageMarks: 16,
  },
  {
    id: 'mod-bio-4',
    subjectId: 'sub-bio',
    moduleNumber: 4,
    title: 'Biosensors & Biomedical Instrumentation',
    description: 'Biosensor transducers, optical/pressure/chemical sensors, heart physiology, EEG, ECG, Ultrasound, MRI, and Tomography.',
    topics: ['Biosensor Transduction Principles', 'ECG, EEG & Physiological Monitoring', 'MRI & Tomographic Imaging'],
    weightageMarks: 16,
  },
  {
    id: 'mod-bio-5',
    subjectId: 'sub-bio',
    moduleNumber: 5,
    title: 'Systems Biology & Biomechanics',
    description: 'Metabolic pathway dynamics, musculoskeletal/cardiovascular mechanics, biocompatible materials, implants, and tissue engineering.',
    topics: ['Metabolic Network Modeling', 'Musculoskeletal & Blood Flow Models', 'Biomaterial Biocompatibility', 'Tissue Engineering'],
    weightageMarks: 16,
  },

  // --- Structured Programming Methodology (316U06C107) ---
  {
    id: 'mod-spm-1',
    subjectId: 'sub-spm',
    moduleNumber: 1,
    title: 'Algorithms & Structured Programming Basics',
    description: 'Problem definition, algorithms, flowcharts, pseudocode, SDLC, data types, identifiers, operator precedence, and type conversions.',
    topics: ['Algorithms & Flowchart Logic', 'Data Types & Variables', 'Operators & Precedence Rules', 'Type Conversion'],
    weightageMarks: 16,
  },
  {
    id: 'mod-spm-2',
    subjectId: 'sub-spm',
    moduleNumber: 2,
    title: 'Program Control Structures',
    description: 'Two-way and multiway selection (if-else, switch-case), looping constructs (for, while, do-while), flags, and code readability.',
    topics: ['Selection & Branching (if-else, switch)', 'Iteration & Loops (for, while)', 'Flag Concepts & Best Practices'],
    weightageMarks: 16,
  },
  {
    id: 'mod-spm-3',
    subjectId: 'sub-spm',
    moduleNumber: 3,
    title: 'Arrays & String Processing',
    description: '1D and multidimensional array operations, character arrays, string declarations, and string processing functions from scratch.',
    topics: ['1D & 2D Array Operations', 'String Handling from Scratch', 'Memory Layout of Arrays'],
    weightageMarks: 18,
  },
  {
    id: 'mod-spm-4',
    subjectId: 'sub-spm',
    moduleNumber: 4,
    title: 'Functions, Structures & Pointers',
    description: 'User-defined functions, pass by value, recursion, structures, unions, pointer declaration, pointer arithmetic, pass by reference, and dynamic memory.',
    topics: ['Modular Functions & Recursion', 'Structures & Unions', 'Pointers & Memory Addresses', 'Pass by Reference'],
    weightageMarks: 20,
  },

  // --- SEMESTER II MODULES ---
  // --- Applied Mathematics – II (316U06C201) ---
  {
    id: 'mod-m2-1',
    subjectId: 'sub-math2',
    moduleNumber: 1,
    title: 'First Order Linear Differential Equations',
    description: 'Exact differential equations, integrating factors, linear differential equations, and applications to orthogonal trajectories and cooling laws.',
    topics: ['Exact ODEs', 'Integrating Factors Rules', 'Linear Equations & Bernoulli', 'Orthogonal Trajectories'],
    weightageMarks: 18,
  },
  {
    id: 'mod-m2-2',
    subjectId: 'sub-math2',
    moduleNumber: 2,
    title: 'Higher Order Linear ODEs & Special Methods',
    description: 'Complementary functions, particular integrals for standard functions, Cauchy-Euler equations, and method of variation of parameters.',
    topics: ['Higher Order Constant Coefficient ODEs', 'Cauchy-Euler Equations', 'Method of Variation of Parameters'],
    weightageMarks: 20,
  },
  {
    id: 'mod-m2-3',
    subjectId: 'sub-math2',
    moduleNumber: 3,
    title: 'Beta, Gamma Functions & DUIS',
    description: 'Definitions, standard transformation properties of Beta and Gamma functions, and Differentiation Under the Integral Sign (DUIS).',
    topics: ['Beta & Gamma Functions Properties', 'Relation Between Beta & Gamma', 'Differentiation Under Integral Sign (DUIS)'],
    weightageMarks: 16,
  },
  {
    id: 'mod-m2-4',
    subjectId: 'sub-math2',
    moduleNumber: 4,
    title: 'Double Integrals & Area Computation',
    description: 'Double integrals in Cartesian and polar coordinates, change of order of integration, and area computation of plane curves.',
    topics: ['Cartesian & Polar Double Integrals', 'Change of Order of Integration', 'Area Calculations'],
    weightageMarks: 18,
  },
  {
    id: 'mod-m2-5',
    subjectId: 'sub-math2',
    moduleNumber: 5,
    title: 'Triple Integrals & Vector Calculus',
    description: 'Triple integrals in Cartesian, cylindrical, spherical polar coordinates, volume computation, gradient, divergence, curl, and flux theorems.',
    topics: ['Triple Integrals & Volume', 'Cylindrical & Spherical Coordinates', 'Gradient, Divergence & Curl', 'Green & Gauss Theorems'],
    weightageMarks: 18,
  },

  // --- Environmental Science (316U06C204) ---
  {
    id: 'mod-evs-1',
    subjectId: 'sub-evs',
    moduleNumber: 1,
    title: 'Ecosystems & Biodiversity Conservation',
    description: 'Structure and function of ecosystems, energy flow, food chains, biodiversity hotspots, and conservation strategies.',
    topics: ['Ecosystem Dynamics & Food Webs', 'Biodiversity Hotspots & Threats', 'In-situ & Ex-situ Conservation'],
    weightageMarks: 16,
  },
  {
    id: 'mod-evs-2',
    subjectId: 'sub-evs',
    moduleNumber: 2,
    title: 'Pollution Control & Waste Management',
    description: 'Air, water, soil, noise pollution, control technologies, solid waste management, e-waste handling, and circular economy.',
    topics: ['Air & Water Pollution Technologies', 'Solid & Hazardous Waste Management', 'E-Waste Recycling & Circular Economy'],
    weightageMarks: 18,
  },
  {
    id: 'mod-evs-3',
    subjectId: 'sub-evs',
    moduleNumber: 3,
    title: 'Climate Change & Sustainable Energy',
    description: 'Greenhouse effect, global warming, carbon footprint reduction, solar, wind, and green hydrogen energy systems.',
    topics: ['Global Warming & Carbon Footprints', 'Solar & Wind Energy Systems', 'Green Hydrogen & Clean Fuels'],
    weightageMarks: 16,
  },
  {
    id: 'mod-evs-4',
    subjectId: 'sub-evs',
    moduleNumber: 4,
    title: 'Environmental Legislation & Green Audits',
    description: 'Environmental protection acts, ISO 14001, Environmental Impact Assessment (EIA), and sustainable engineering practices.',
    topics: ['Environmental Protection Act (EPA)', 'Environmental Impact Assessment (EIA)', 'Green Building & Carbon Offsets'],
    weightageMarks: 16,
  },

  // --- Object-Oriented Programming Methodology (316U06C205) ---
  {
    id: 'mod-oop-1',
    subjectId: 'sub-oop',
    moduleNumber: 1,
    title: 'Classes, Objects & Data Encapsulation',
    description: 'Principles of object-oriented design, class declarations, object instantiation, access specifiers, static members, and friend functions.',
    topics: ['Class Declarations & Member Functions', 'Access Specifiers (public/private/protected)', 'Static Members & Friend Functions'],
    weightageMarks: 16,
  },
  {
    id: 'mod-oop-2',
    subjectId: 'sub-oop',
    moduleNumber: 2,
    title: 'Constructors, Destructors & Operator Overloading',
    description: 'Default, parameterized, and copy constructors, destructor cleanup, unary and binary operator overloading, and type conversion.',
    topics: ['Constructors (Default, Parameterized, Copy)', 'Destructor Resource Management', 'Unary & Binary Operator Overloading'],
    weightageMarks: 18,
  },
  {
    id: 'mod-oop-3',
    subjectId: 'sub-oop',
    moduleNumber: 3,
    title: 'Inheritance Hierarchies & Polymorphism',
    description: 'Single, multiple, multilevel, hierarchical, and hybrid inheritance, virtual base classes, virtual functions, abstract classes, and runtime polymorphism.',
    topics: ['Inheritance Types & Base Initialization', 'Virtual Functions & Runtime Binding', 'Abstract Classes & Pure Virtual Functions'],
    weightageMarks: 20,
  },
  {
    id: 'mod-oop-4',
    subjectId: 'sub-oop',
    moduleNumber: 4,
    title: 'Templates, Exceptions & STL Containers',
    description: 'Function and class templates, try-catch exception handling, standard template library (vector, list, map), and iterators.',
    topics: ['Function & Class Templates', 'Exception Handling Mechanisms', 'STL Vectors, Maps & Iterators'],
    weightageMarks: 18,
  },

  // --- Presentation and Communication Skills (316U06T201) ---
  {
    id: 'mod-pcs-1',
    subjectId: 'sub-pcs',
    moduleNumber: 1,
    title: 'Business & Professional Correspondence',
    description: 'Formal business emails, professional memos, cover letters, and organizational communication channels.',
    topics: ['Email Etiquette & Structure', 'Cover Letter & Resume Writing', 'Organizational Communication Channels'],
    weightageMarks: 16,
  },
  {
    id: 'mod-pcs-2',
    subjectId: 'sub-pcs',
    moduleNumber: 2,
    title: 'Technical Report Drafting & Presentations',
    description: 'Structure of engineering technical reports, visual data representation, and high-impact presentation delivery techniques.',
    topics: ['Technical Report Architecture', 'Visual Aids & Slide Design', 'Oral Presentation Delivery'],
    weightageMarks: 18,
  },
  {
    id: 'mod-pcs-3',
    subjectId: 'sub-pcs',
    moduleNumber: 3,
    title: 'Group Discussions, Interviews & Professional Ethics',
    description: 'Group discussion dynamics, non-verbal communication, interview preparation strategies, and engineering professional ethics.',
    topics: ['Group Discussion Leadership', 'Interview Question Strategies', 'Engineering Ethics & Professionalism'],
    weightageMarks: 16,
  }
];

export const INITIAL_RESOURCES: AcademicResource[] = [
  // --- Applied Mathematics – I Module-Wise Lecture Notes & Parts ---
  {
    id: 'res-math1-mod1-p1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-1',
    title: 'Rank of Matrix and System of Equations (Part 1)',
    type: 'notes',
    filePath: '/sample-resources/maths1_matrix_rank_p1.pdf',
    fileName: 'AM1_Mod1_Matrix_Rank_Part1.pdf',
    fileSizeBytes: 520000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1840,
    tags: ['Sem1', '316U06C101', 'Rank of Matrix', 'Row Echelon'],
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'res-math1-mod1-p2',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-1',
    title: 'Consistency of Linear Equations & Iterative Methods (Part 2)',
    type: 'notes',
    filePath: '/sample-resources/maths1_matrix_rank_p2.pdf',
    fileName: 'AM1_Mod1_Linear_Systems_Part2.pdf',
    fileSizeBytes: 680000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1520,
    tags: ['Sem1', 'Gauss-Seidel', 'Jacobi Method'],
    createdAt: '2025-01-12T10:00:00Z',
  },
  {
    id: 'res-math1-mod2-p1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation and Application (Part 1)',
    type: 'notes',
    filePath: '/sample-resources/maths1_partial_diff_p1.pdf',
    fileName: 'AM1_Mod2_Partial_Diff_Part1.pdf',
    fileSizeBytes: 559000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2450,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-14T10:00:00Z',
  },
  {
    id: 'res-math1-mod2-p2',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation and Application (Part 2)',
    type: 'notes',
    filePath: '/sample-resources/maths1_partial_diff_p2.pdf',
    fileName: 'AM1_Mod2_Partial_Diff_Part2.pdf',
    fileSizeBytes: 453000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2210,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-15T11:00:00Z',
  },
  {
    id: 'res-math1-mod2-p3',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation and Application (Part 3)',
    type: 'notes',
    filePath: '/sample-resources/maths1_partial_diff_p3.pdf',
    fileName: 'AM1_Mod2_Partial_Diff_Part3.pdf',
    fileSizeBytes: 233000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1980,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-16T12:00:00Z',
  },
  {
    id: 'res-math1-mod2-p4',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation and Application (Part 4)',
    type: 'notes',
    filePath: '/sample-resources/maths1_partial_diff_p4.pdf',
    fileName: 'AM1_Mod2_Partial_Diff_Part4.pdf',
    fileSizeBytes: 293000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2130,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-17T14:00:00Z',
  },
  {
    id: 'res-math1-formula-1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation, Jacobians & Maxima-Minima Quick Formula Sheet',
    type: 'formula_sheet',
    filePath: '/sample-resources/maths1_partial_diff_formulas.pdf',
    fileName: 'Maths1_Partial_Diff_Formula_Sheet.pdf',
    fileSizeBytes: 890000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2980,
    tags: ['Sem1', 'Formula Sheet', 'Jacobians', 'Euler Theorem'],
    createdAt: '2025-01-18T14:30:00Z',
  },
  {
    id: 'res-math1-mod3-p1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-3',
    title: 'Homogeneous Functions & Euler’s Theorem Derivations (Part 1)',
    type: 'notes',
    filePath: '/sample-resources/maths1_euler_p1.pdf',
    fileName: 'AM1_Mod3_Euler_Theorem_Part1.pdf',
    fileSizeBytes: 410000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1650,
    tags: ['Sem1', 'Euler Theorem', 'Homogeneous'],
    createdAt: '2025-01-19T10:00:00Z',
  },
  {
    id: 'res-math1-mod4-p1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-4',
    title: 'Linear Differential Equations of First & Higher Order (Part 1)',
    type: 'notes',
    filePath: '/sample-resources/maths1_ode_p1.pdf',
    fileName: 'AM1_Mod4_Linear_ODEs_Part1.pdf',
    fileSizeBytes: 620000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1890,
    tags: ['Sem1', 'ODEs', 'Particular Integrals'],
    createdAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 'res-math1-mod5-p1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-5',
    title: 'Complex Numbers, Hyperbolic Functions and Logarithm of Complex Number (Part 1)',
    type: 'notes',
    filePath: '/sample-resources/maths1_complex_p1.pdf',
    fileName: 'AM1_Mod5_Complex_Numbers_Part1.pdf',
    fileSizeBytes: 789000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2670,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-22T10:00:00Z',
  },
  {
    id: 'res-math1-mod5-p2',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-5',
    title: 'Complex Numbers, Hyperbolic Functions and Logarithm of Complex Number (Part 2)',
    type: 'notes',
    filePath: '/sample-resources/maths1_complex_p2.pdf',
    fileName: 'AM1_Mod5_Complex_Numbers_Part2.pdf',
    fileSizeBytes: 438000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2410,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-23T11:00:00Z',
  },
  {
    id: 'res-phy-slides-1',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-1',
    title: 'Thin Film Interference & Newton’s Rings Complete Slides',
    type: 'ppt',
    filePath: '/sample-resources/physics_interference_slides.pptx',
    fileName: 'Physics_Module1_Interference_Slides.pptx',
    fileSizeBytes: 4900000,
    fileMime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Department of Physics',
    isVerified: true,
    downloadsCount: 1620,
    tags: ['Sem1', '316U06C102', 'Interference', 'Newton Rings'],
    createdAt: '2025-01-25T11:20:00Z',
  },
  {
    id: 'res-chem-notes-1',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-1',
    title: 'Industrial Water Treatment (EDTA, Zeolite & Ion Exchange) Complete Notes',
    type: 'notes',
    filePath: '/sample-resources/chemistry_water_treatment.pdf',
    fileName: 'Chemistry_Module1_Water_Treatment.pdf',
    fileSizeBytes: 3100000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Department of Chemistry',
    isVerified: true,
    downloadsCount: 2150,
    tags: ['Sem1', '316U06C103', 'Water Treatment', 'Zeolite'],
    createdAt: '2025-01-28T09:15:00Z',
  },
  {
    id: 'res-bee-notes-1',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-1',
    title: 'DC Network Theorems (Thevenin, Norton & Max Power) Solved Problems',
    type: 'notes',
    filePath: '/sample-resources/bee_dc_theorems_solved.pdf',
    fileName: 'BEE_DC_Theorems_Handwritten_Notes.pdf',
    fileSizeBytes: 3400000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Department of Electrical Engineering',
    isVerified: true,
    downloadsCount: 2450,
    tags: ['Sem1', '316U06C104', 'Thevenin', 'Norton', 'DC Circuits'],
    createdAt: '2025-01-22T09:00:00Z',
  },
  {
    id: 'res-ed-notes-1',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-1',
    title: 'Engineering Drawing First Angle Orthographic Projections Step-by-Step Guide',
    type: 'notes',
    filePath: '/sample-resources/ed_orthographic_guide.pdf',
    fileName: 'Engineering_Drawing_Orthographic_Projections.pdf',
    fileSizeBytes: 5200000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Department of Mechanical Engineering',
    isVerified: true,
    downloadsCount: 2890,
    tags: ['Sem1', '316U06C105', 'Orthographic', 'First Angle'],
    createdAt: '2025-01-30T10:00:00Z',
  },
  {
    id: 'res-bio-notes-1',
    subjectId: 'sub-bio',
    moduleId: 'mod-bio-1',
    title: 'Biology for Engineers Biomolecules, Enzyme Kinetics & Biosensors Handbook',
    type: 'notes',
    filePath: '/sample-resources/bio_engineers_handbook.pdf',
    fileName: 'Biology_for_Engineers_Study_Guide.pdf',
    fileSizeBytes: 2900000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Life Sciences',
    isVerified: true,
    downloadsCount: 1980,
    tags: ['Sem1', '316U06C106', 'Biomolecules', 'Biosensors'],
    createdAt: '2025-02-02T12:00:00Z',
  },
  // --- PRACTICE QUESTIONS (MODULE-WISE) ---
  {
    id: 'res-math1-practice-1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-1',
    title: 'Rank of Matrix, Echelon Form & Linear Systems Solved Practice Questions',
    type: 'practice_ques',
    filePath: '/sample-resources/maths1_matrices_practice.pdf',
    fileName: 'AM1_Mod1_Matrices_Practice_Questions.pdf',
    fileSizeBytes: 1450000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2240,
    tags: ['Sem1', 'Practice Questions', 'Matrices', 'Rank'],
    createdAt: '2025-02-03T10:00:00Z',
  },
  {
    id: 'res-math1-practice-2',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation, Jacobians & Maxima-Minima Practice Questions',
    type: 'practice_ques',
    filePath: '/sample-resources/maths1_partial_diff_practice.pdf',
    fileName: 'AM1_Mod2_Partial_Diff_Practice_Questions.pdf',
    fileSizeBytes: 1680000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1980,
    tags: ['Sem1', 'Practice Questions', 'Jacobians', 'Partial Diff'],
    createdAt: '2025-02-04T11:00:00Z',
  },
  {
    id: 'res-bee-practice-1',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-1',
    title: 'DC Network Circuit Theorems (Thevenin & Norton) Solved Practice Questions',
    type: 'practice_ques',
    filePath: '/sample-resources/bee_theorems_practice.pdf',
    fileName: 'BEE_Mod1_Theorems_Practice_Problems.pdf',
    fileSizeBytes: 1820000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Department of Electrical Engineering',
    isVerified: true,
    downloadsCount: 2310,
    tags: ['Sem1', 'Practice Questions', 'Thevenin', 'Norton'],
    createdAt: '2025-02-05T09:00:00Z',
  },
  // --- YEAR-WISE SUBJECT PYQS (MID SEM & END SEM) ---
  {
    id: 'res-math1-pyq-endsem-24',
    subjectId: 'sub-math1',
    moduleId: undefined,
    title: 'Applied Mathematics – I End-Semester University Exam Question Paper (2024-25)',
    type: 'pyq',
    examType: 'end_sem',
    examYear: '2024-25',
    filePath: '/sample-resources/maths1_pyq_endsem_2024.pdf',
    fileName: 'AM1_EndSem_Question_Paper_2024_25.pdf',
    fileSizeBytes: 2100000,
    fileMime: 'application/pdf',
    academicYear: '2024-2025',
    scheme: 'REV_2025',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 4520,
    tags: ['PYQ', 'End Sem', '2024-25', 'Maths1', 'Official'],
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'res-math1-pyq-midsem-24',
    subjectId: 'sub-math1',
    moduleId: undefined,
    title: 'Applied Mathematics – I Mid-Semester Exam Question Paper (2024-25)',
    type: 'pyq',
    examType: 'mid_sem',
    examYear: '2024-25',
    filePath: '/sample-resources/maths1_pyq_midsem_2024.pdf',
    fileName: 'AM1_MidSem_Question_Paper_2024_25.pdf',
    fileSizeBytes: 1400000,
    fileMime: 'application/pdf',
    academicYear: '2024-2025',
    scheme: 'REV_2025',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 3890,
    tags: ['PYQ', 'Mid Sem', '2024-25', 'Maths1', 'Official'],
    createdAt: '2024-10-15T10:00:00Z',
  },
  {
    id: 'res-math1-pyq-endsem-23',
    subjectId: 'sub-math1',
    moduleId: undefined,
    title: 'Applied Mathematics – I End-Semester University Exam Question Paper (2023-24)',
    type: 'pyq',
    examType: 'end_sem',
    examYear: '2023-24',
    filePath: '/sample-resources/maths1_pyq_endsem_2023.pdf',
    fileName: 'AM1_EndSem_Question_Paper_2023_24.pdf',
    fileSizeBytes: 1980000,
    fileMime: 'application/pdf',
    academicYear: '2023-2024',
    scheme: 'REV_2024',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 3650,
    tags: ['PYQ', 'End Sem', '2023-24', 'Maths1', 'Official'],
    createdAt: '2024-01-12T10:00:00Z',
  },
  {
    id: 'res-phy-pyq-endsem-24',
    subjectId: 'sub-phy',
    moduleId: undefined,
    title: 'Engineering Physics End-Semester Exam Question Paper (2024-25)',
    type: 'pyq',
    examType: 'end_sem',
    examYear: '2024-25',
    filePath: '/sample-resources/physics_pyq_endsem_2024.pdf',
    fileName: 'Physics_EndSem_Question_Paper_2024_25.pdf',
    fileSizeBytes: 1850000,
    fileMime: 'application/pdf',
    academicYear: '2024-2025',
    scheme: 'REV_2025',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 3120,
    tags: ['PYQ', 'End Sem', '2024-25', 'Physics', '316U06C102'],
    createdAt: '2025-01-11T10:00:00Z',
  },
  {
    id: 'res-bee-pyq-endsem-24',
    subjectId: 'sub-bee',
    moduleId: undefined,
    title: 'Basic Electrical Engineering End-Semester Exam Question Paper (2024-25)',
    type: 'pyq',
    examType: 'end_sem',
    examYear: '2024-25',
    filePath: '/sample-resources/bee_pyq_endsem_2024.pdf',
    fileName: 'BEE_EndSem_Question_Paper_2024_25.pdf',
    fileSizeBytes: 2200000,
    fileMime: 'application/pdf',
    academicYear: '2024-2025',
    scheme: 'REV_2025',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 4210,
    tags: ['PYQ', 'End Sem', '2024-25', 'BEE', '316U06C104'],
    createdAt: '2025-01-12T10:00:00Z',
  },
  {
    id: 'res-spm-pyq-endsem-24',
    subjectId: 'sub-spm',
    moduleId: undefined,
    title: 'Structured Programming Methodology (C) End-Semester Exam Paper (2024-25)',
    type: 'pyq',
    examType: 'end_sem',
    examYear: '2024-25',
    filePath: '/sample-resources/spm_pyq_endsem_2024.pdf',
    fileName: 'SPM_EndSem_Question_Paper_2024_25.pdf',
    fileSizeBytes: 2450000,
    fileMime: 'application/pdf',
    academicYear: '2024-2025',
    scheme: 'REV_2025',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 3980,
    tags: ['PYQ', 'End Sem', '2024-25', 'SPM', '316U06C107'],
    createdAt: '2025-01-14T10:00:00Z',
  }
];

export const INITIAL_YOUTUBE_RESOURCES: YouTubeResource[] = [
  // --- Applied Mathematics – I ---
  {
    id: 'yt-math1-master',
    subjectId: 'sub-math1',
    moduleId: undefined,
    title: 'Applied Mathematics – I Full Course Master Playlist',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=wH2uY-n5_sQ',
    videoId: 'wH2uY-n5_sQ',
    isPlaylist: true,
    duration: 'Full Syllabus (42 Lectures)',
    description: 'Complete course master playlist covering Matrices, Calculus, Partial Differentiation, ODEs, and Complex Numbers.',
    tags: ['Maths1', 'Full Course', '316U06C101'],
    customThumbnail: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-05T10:00:00Z',
  },
  {
    id: 'yt-math1-matrices',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-1',
    title: 'Module 1: Matrices, Rank of Matrix & Normal Form Playlist',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=kYJzX4M-s6o',
    videoId: 'kYJzX4M-s6o',
    isPlaylist: true,
    duration: 'Full Playlist (14 Videos)',
    description: 'Echelon form, normal form, linear systems consistency, Gauss-Seidel, and Jacobi iteration methods.',
    tags: ['Maths1', 'Mod 1', 'Matrices', 'Rank'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-06T10:00:00Z',
  },
  {
    id: 'yt-math1-partial-diff',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Module 2: Partial Differentiation, Jacobians & Maxima-Minima',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=U9l1K5uQy8Y',
    videoId: 'U9l1K5uQy8Y',
    isPlaylist: true,
    duration: 'Full Playlist (16 Videos)',
    description: 'Higher-order partial derivatives, composite chain rule, Jacobians, and Lagrange multipliers.',
    tags: ['Maths1', 'Mod 2', 'Partial Diff', 'Jacobians'],
    customThumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-08T12:00:00Z',
  },
  {
    id: 'yt-math1-euler',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-3',
    title: 'Module 3: Homogeneous Functions & Euler’s Theorem Derivations',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=2-fN8r4sU-s',
    videoId: '2-fN8r4sU-s',
    isPlaylist: false,
    duration: '34:20',
    description: 'Step-by-step proofs of Euler’s theorem with university exam derivations.',
    tags: ['Maths1', 'Mod 3', 'Euler Theorem', 'Homogeneous'],
    customThumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-10T11:00:00Z',
  },
  {
    id: 'yt-math1-ode',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-4',
    title: 'Module 4: Linear ODEs of Higher Order & Particular Integrals (CF + PI)',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=3-lQ4zWl4qQ',
    videoId: '3-lQ4zWl4qQ',
    isPlaylist: true,
    duration: 'Full Playlist (12 Videos)',
    description: 'Exact differential equations, complementary functions, and variation of parameters method.',
    tags: ['Maths1', 'Mod 4', 'ODEs', 'Differential Equations'],
    customThumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-12T09:00:00Z',
  },
  {
    id: 'yt-math1-complex',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-5',
    title: 'Module 5: Complex Numbers, De Moivre’s Theorem & Hyperbolic Functions',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=G7j2P3l9M2w',
    videoId: 'G7j2P3l9M2w',
    isPlaylist: true,
    duration: 'Full Playlist (18 Videos)',
    description: 'De Moivre’s theorem, roots of complex numbers, circular and hyperbolic functions, and logarithms.',
    tags: ['Maths1', 'Mod 5', 'Complex Numbers', 'De Moivre'],
    customThumbnail: 'https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-14T10:00:00Z',
  },

  // --- Engineering Physics ---
  {
    id: 'yt-phy-optics',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-1',
    title: 'Wave Optics: Thin Film Interference & Newton’s Rings Engineering Physics',
    channelName: 'Physics Simplified',
    youtubeUrl: 'https://www.youtube.com/watch?v=gT8wNlV_V_E',
    videoId: 'gT8wNlV_V_E',
    isPlaylist: false,
    duration: '35:10',
    description: 'Derivations of thin film interference, wedge films, and Newton’s rings experimental setup.',
    tags: ['Physics', '316U06C102', 'Interference', 'Newton Rings'],
    customThumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-15T11:00:00Z',
  },
  {
    id: 'yt-phy-lasers',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-2',
    title: 'Photonics: Lasers, Einstein Coefficients & Optical Fiber Cable Derivations',
    channelName: 'Physics Simplified',
    youtubeUrl: 'https://www.youtube.com/watch?v=0k52fM43d7s',
    videoId: '0k52fM43d7s',
    isPlaylist: true,
    duration: 'Full Playlist (10 Videos)',
    description: 'Laser principles, population inversion, optical resonator, step index numerical aperture, and attenuation.',
    tags: ['Physics', 'Mod 2', 'Lasers', 'Fiber Optics'],
    customThumbnail: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-16T11:00:00Z',
  },
  {
    id: 'yt-phy-quantum',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-3',
    title: 'Quantum Mechanics: De Broglie Hypothesis & Schrodinger Wave Equation',
    channelName: 'Physics Simplified',
    youtubeUrl: 'https://www.youtube.com/watch?v=yW6S4WzW62Y',
    videoId: 'yW6S4WzW62Y',
    isPlaylist: false,
    duration: '26:40',
    description: 'Wave-particle duality, phase & group velocities, and time-independent Schrodinger equation.',
    tags: ['Physics', 'Mod 3', 'Quantum', 'Schrodinger'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-17T11:00:00Z',
  },
  {
    id: 'yt-phy-semiconductors',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-4',
    title: 'Semiconductors & Electrodynamics: Fermi Level & Maxwell Equations',
    channelName: 'Physics Simplified',
    youtubeUrl: 'https://www.youtube.com/watch?v=8S_6h04n1fM',
    videoId: '8S_6h04n1fM',
    isPlaylist: false,
    duration: '31:10',
    description: 'Intrinsic & extrinsic semiconductors, Fermi level, Hall effect, and differential Maxwell equations.',
    tags: ['Physics', 'Mod 4', 'Semiconductors', 'Maxwell'],
    customThumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-17T12:00:00Z',
  },

  // --- Engineering Chemistry ---
  {
    id: 'yt-chem-water',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-1',
    title: 'Industrial Water Treatment (EDTA, Zeolite & Ion Exchange) Complete Masterclass',
    channelName: 'Ekeeda Chemistry',
    youtubeUrl: 'https://www.youtube.com/watch?v=de9vwMGgTvg',
    videoId: 'de9vwMGgTvg',
    isPlaylist: true,
    duration: 'Full Playlist (12 Videos)',
    description: 'Types of hardness, EDTA titrations, zeolite softening, BOD/COD calculations, and reverse osmosis.',
    tags: ['Chemistry', '316U06C103', 'Water Treatment', 'EDTA'],
    customThumbnail: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T10:00:00Z',
  },
  {
    id: 'yt-chem-green',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-2',
    title: '12 Principles of Green Chemistry & Sustainable Synthetic Reactions',
    channelName: 'Chemistry Hub',
    youtubeUrl: 'https://www.youtube.com/watch?v=9_H8XWz9J_g',
    videoId: '9_H8XWz9J_g',
    isPlaylist: false,
    duration: '42:15',
    description: 'Green metrics, atom economy, supercritical CO2, ionic liquids, and microwave-assisted synthesis.',
    tags: ['Chemistry', 'Mod 2', 'Green Chemistry', 'Atom Economy'],
    customThumbnail: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-19T10:00:00Z',
  },
  {
    id: 'yt-chem-phase',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-3',
    title: 'Phase Rule & Two Component Lead-Silver Eutectic System',
    channelName: 'Chemistry Hub',
    youtubeUrl: 'https://www.youtube.com/watch?v=7O2sH_P5U48',
    videoId: '7O2sH_P5U48',
    isPlaylist: false,
    duration: '31:20',
    description: 'Gibbs phase rule terms, degree of freedom, and lead-silver desilverization phase diagram.',
    tags: ['Chemistry', 'Mod 3', 'Phase Rule', 'Lead Silver'],
    customThumbnail: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-19T11:00:00Z',
  },
  {
    id: 'yt-chem-corrosion',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-4',
    title: 'Corrosion Mechanisms, Lithium-Ion Batteries & Supercapacitors',
    channelName: 'Chemistry Hub',
    youtubeUrl: 'https://www.youtube.com/watch?v=H74S9zRk-8M',
    videoId: 'H74S9zRk-8M',
    isPlaylist: false,
    duration: '33:00',
    description: 'Electrochemical wet corrosion, cathodic protection, and Lithium-ion battery working principles.',
    tags: ['Chemistry', 'Mod 4', 'Corrosion', 'Batteries'],
    customThumbnail: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-19T12:00:00Z',
  },

  // --- Basic Electrical Engineering ---
  {
    id: 'yt-bee-master',
    subjectId: 'sub-bee',
    moduleId: undefined,
    title: 'Basic Electrical Engineering (BEE) Complete Subject Playlist',
    channelName: 'Gate Smashers',
    youtubeUrl: 'https://www.youtube.com/watch?v=0h3jP26-q5k',
    videoId: '0h3jP26-q5k',
    isPlaylist: true,
    duration: 'Full Syllabus (36 Lectures)',
    description: 'Master course playlist covering DC Circuits, AC Fundamentals, 3-Phase Systems, Single-Phase Transformers, and Electrical Machines.',
    tags: ['Master Playlist', 'BEE', 'Full Course'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-08T10:00:00Z',
  },
  {
    id: 'yt-bee-theorems',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-1',
    title: 'Thevenin’s & Norton’s Theorems - Step-by-Step Circuit Reduction',
    channelName: 'Gate Smashers',
    youtubeUrl: 'https://www.youtube.com/watch?v=0h3jP26-q5k',
    videoId: '0h3jP26-q5k',
    isPlaylist: false,
    duration: '28:40',
    description: 'Intuitive breakdown of DC network circuit reduction, independent sources, and maximum power transfer.',
    tags: ['BEE', '316U06C104', 'Thevenin', 'Norton', 'DC Circuits'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T09:00:00Z',
  },
  {
    id: 'yt-bee-ac',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-2',
    title: 'AC Fundamentals: R-L-C Series Resonance & Phasor Diagrams',
    channelName: 'Gate Smashers',
    youtubeUrl: 'https://www.youtube.com/watch?v=ZtI9z-V3P_U',
    videoId: 'ZtI9z-V3P_U',
    isPlaylist: false,
    duration: '36:00',
    description: 'Sinusoidal AC quantities, RMS and average values, form factor, and series resonance impedance.',
    tags: ['BEE', 'Mod 2', 'AC Circuits', 'Resonance'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T10:00:00Z',
  },
  {
    id: 'yt-bee-threephase',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-3',
    title: '3-Phase AC Systems: Star-Delta Connections & Two-Wattmeter Method',
    channelName: 'Gate Smashers',
    youtubeUrl: 'https://www.youtube.com/watch?v=UfG1zTj0j8M',
    videoId: 'UfG1zTj0j8M',
    isPlaylist: false,
    duration: '38:15',
    description: 'Balanced star and delta connected systems, line vs phase voltages, and two-wattmeter power measurement.',
    tags: ['BEE', 'Mod 3', 'Three Phase', 'Star Delta'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T11:00:00Z',
  },
  {
    id: 'yt-bee-machines',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-4',
    title: 'Transformers & Induction Motors: Construction, Working & EMF Equation',
    channelName: 'Gate Smashers',
    youtubeUrl: 'https://www.youtube.com/watch?v=0h3jP26-q5k',
    videoId: '0h3jP26-q5k',
    isPlaylist: false,
    duration: '34:10',
    description: 'Single-phase transformer EMF equation, losses, efficiency, and 3-phase induction motor rotation principle.',
    tags: ['BEE', 'Mod 4', 'Transformers', 'Induction Motor'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T12:00:00Z',
  },

  // --- Engineering Drawing ---
  {
    id: 'yt-ed-ortho',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-1',
    title: 'Engineering Drawing: Orthographic Projections & Sectional Views Step-by-Step',
    channelName: 'Tikles Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=gT8wNlV_V_E',
    videoId: 'gT8wNlV_V_E',
    isPlaylist: false,
    duration: '38:45',
    description: 'Front view, top view, and side view first-angle projection methods for 3D engineering components.',
    tags: ['Engineering Drawing', '316U06C105', 'Orthographic', 'Projections'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T14:30:00Z',
  },
  {
    id: 'yt-ed-lines',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-2',
    title: 'Projections of Straight Lines & Geometric Planes',
    channelName: 'Tikles Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=0k52fM43d7s',
    videoId: '0k52fM43d7s',
    isPlaylist: false,
    duration: '36:10',
    description: 'Lines inclined to both HP and VP, true lengths, and traces of regular polygonal planes.',
    tags: ['Engineering Drawing', 'Mod 2', 'Lines', 'Planes'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T15:00:00Z',
  },
  {
    id: 'yt-ed-solids',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-3',
    title: 'Projections of Solids & Lateral Surface Development',
    channelName: 'Tikles Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=yW6S4WzW62Y',
    videoId: 'yW6S4WzW62Y',
    isPlaylist: false,
    duration: '35:00',
    description: 'Prisms, pyramids, cylinders, cones, and radial line developments of truncated solids.',
    tags: ['Engineering Drawing', 'Mod 3', 'Solids', 'Development'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T15:30:00Z',
  },
  {
    id: 'yt-ed-isometric',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-4',
    title: 'Isometric Projections & Machine Block Views',
    channelName: 'Tikles Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=8S_6h04n1fM',
    videoId: '8S_6h04n1fM',
    isPlaylist: false,
    duration: '34:50',
    description: 'Isometric scale construction, isometric views vs projections of machine parts.',
    tags: ['Engineering Drawing', 'Mod 4', 'Isometric', 'Views'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T16:00:00Z',
  },

  // --- Structured Programming Methodology (C) ---
  {
    id: 'yt-spm-master',
    subjectId: 'sub-spm',
    title: 'Structured Programming Methodology in C: Complete Syllabus Master Playlist',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://www.youtube.com/watch?v=YXcgD8hRHYY',
    videoId: 'YXcgD8hRHYY',
    isPlaylist: true,
    duration: 'Full Playlist (All Modules)',
    description: 'Complete syllabus C programming series covering Problem Solving, Flowcharts, Loops, Arrays, Strings, Functions, Pointers, and Dynamic Memory allocation.',
    tags: ['SPM', '316U06C107', 'C Programming', 'Full Syllabus', 'Sem1'],
    customThumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-25T14:00:00Z',
  },
  {
    id: 'yt-spm-mod1',
    subjectId: 'sub-spm',
    moduleId: 'mod-spm-1',
    title: 'Module 1: Algorithms, Flowcharts & Basic C Syntax',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://www.youtube.com/watch?v=YXcgD8hRHYY',
    videoId: 'YXcgD8hRHYY',
    isPlaylist: false,
    duration: '24:10',
    description: 'Flowchart logic, variable types, operators, and basic compilation.',
    tags: ['SPM', 'Mod 1', 'C Basics'],
    customThumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-25T14:30:00Z',
  },
  {
    id: 'yt-spm-mod2',
    subjectId: 'sub-spm',
    moduleId: 'mod-spm-2',
    title: 'Module 2: Branching (if-else) & Loops (for, while, do-while)',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://www.youtube.com/watch?v=YXcgD8hRHYY',
    videoId: 'YXcgD8hRHYY',
    isPlaylist: false,
    duration: '28:30',
    description: 'Selection structures, switch statements, and loop iterations.',
    tags: ['SPM', 'Mod 2', 'Loops'],
    customThumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-25T15:00:00Z',
  },
  {
    id: 'yt-spm-mod3',
    subjectId: 'sub-spm',
    moduleId: 'mod-spm-3',
    title: 'Module 3: Arrays & String Processing in C',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://www.youtube.com/watch?v=YXcgD8hRHYY',
    videoId: 'YXcgD8hRHYY',
    isPlaylist: false,
    duration: '29:30',
    description: '1D/2D arrays, matrix arithmetic, character arrays, and string manipulations.',
    tags: ['SPM', 'Mod 3', 'Arrays', 'Strings'],
    customThumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-25T15:30:00Z',
  },
  {
    id: 'yt-spm-mod4',
    subjectId: 'sub-spm',
    moduleId: 'mod-spm-4',
    title: 'Module 4: Functions, Pointers & Dynamic Memory (malloc/free)',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://www.youtube.com/watch?v=YXcgD8hRHYY',
    videoId: 'YXcgD8hRHYY',
    isPlaylist: false,
    duration: '38:00',
    description: 'Pass by value vs reference, pointers arithmetic, memory allocation, and structures.',
    tags: ['SPM', 'Mod 4', 'Pointers', 'Functions'],
    customThumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-25T16:00:00Z',
  },

  // --- Semester 2 Courses ---
  {
    id: 'yt-math2-ode',
    subjectId: 'sub-math2',
    moduleId: 'mod-m2-1',
    title: 'Applied Mathematics – II: First Order Differential Equations Complete Playlist',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=3-lQ4zWl4qQ',
    videoId: '3-lQ4zWl4qQ',
    isPlaylist: true,
    duration: 'Full Playlist (12 Videos)',
    description: 'Exact differential equations, integrating factors, linear ODEs, and orthogonal trajectories.',
    tags: ['Maths2', '316U06C201', 'Differential Equations', 'ODE', 'Sem2'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'yt-math2-mod2',
    subjectId: 'sub-math2',
    moduleId: 'mod-m2-2',
    title: 'Module 2: Higher Order Linear ODEs & Cauchy-Euler Equations',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=U9l1K5uQy8Y',
    videoId: 'U9l1K5uQy8Y',
    isPlaylist: false,
    duration: '34:20',
    description: 'Complementary functions, particular integrals, and variation of parameters.',
    tags: ['Maths2', 'Mod 2', 'Higher Order ODEs'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-01T11:00:00Z',
  },
  {
    id: 'yt-math2-mod3',
    subjectId: 'sub-math2',
    moduleId: 'mod-m2-3',
    title: 'Module 3: Beta, Gamma Functions & DUIS',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=2-fN8r4sU-s',
    videoId: '2-fN8r4sU-s',
    isPlaylist: false,
    duration: '28:40',
    description: 'Properties of Beta and Gamma functions, DUIS differentiation technique.',
    tags: ['Maths2', 'Mod 3', 'Beta Gamma', 'DUIS'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-01T12:00:00Z',
  },
  {
    id: 'yt-math2-mod4',
    subjectId: 'sub-math2',
    moduleId: 'mod-m2-4',
    title: 'Module 4: Double Integrals & Area Calculations',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=G7j2P3l9M2w',
    videoId: 'G7j2P3l9M2w',
    isPlaylist: false,
    duration: '36:00',
    description: 'Cartesian and polar double integrals, change of order of integration.',
    tags: ['Maths2', 'Mod 4', 'Double Integrals', 'Area'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-01T13:00:00Z',
  },
  {
    id: 'yt-math2-mod5',
    subjectId: 'sub-math2',
    moduleId: 'mod-m2-5',
    title: 'Module 5: Triple Integrals & Vector Calculus',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://www.youtube.com/watch?v=kYJzX4M-s6o',
    videoId: 'kYJzX4M-s6o',
    isPlaylist: false,
    duration: '38:00',
    description: 'Volume integration, gradient, divergence, curl, and Gauss divergence theorem.',
    tags: ['Maths2', 'Mod 5', 'Triple Integrals', 'Vector Calculus'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-01T14:00:00Z',
  },
  {
    id: 'yt-oop-cpp',
    subjectId: 'sub-oop',
    moduleId: 'mod-oop-1',
    title: 'Object-Oriented Programming Methodology (C++): Complete Concepts & STL',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://www.youtube.com/watch?v=z9bZufPHFLU',
    videoId: 'z9bZufPHFLU',
    isPlaylist: true,
    duration: 'Full Playlist (20 Videos)',
    description: 'Classes, objects, constructors, operator overloading, inheritance, virtual functions, and STL containers.',
    tags: ['OOP', '316U06C205', 'C++', 'Inheritance', 'STL'],
    customThumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-05T10:00:00Z',
  },
  {
    id: 'yt-oop-mod2',
    subjectId: 'sub-oop',
    moduleId: 'mod-oop-2',
    title: 'Module 2: Constructors, Destructors & Operator Overloading in C++',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://www.youtube.com/watch?v=z9bZufPHFLU',
    videoId: 'z9bZufPHFLU',
    isPlaylist: false,
    duration: '27:45',
    description: 'Default, parameterized and copy constructors, operator overloading, friend functions.',
    tags: ['OOP', 'Mod 2', 'Constructors', 'Operator Overloading'],
    customThumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-05T11:00:00Z',
  },
  {
    id: 'yt-oop-mod3',
    subjectId: 'sub-oop',
    moduleId: 'mod-oop-3',
    title: 'Module 3: Inheritance Types, Virtual Functions & Polymorphism',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://www.youtube.com/watch?v=z9bZufPHFLU',
    videoId: 'z9bZufPHFLU',
    isPlaylist: false,
    duration: '36:00',
    description: 'Single, multiple, multilevel inheritance, abstract classes, runtime polymorphism, virtual functions.',
    tags: ['OOP', 'Mod 3', 'Inheritance', 'Polymorphism'],
    customThumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-05T12:00:00Z',
  },
  {
    id: 'yt-oop-mod4',
    subjectId: 'sub-oop',
    moduleId: 'mod-oop-4',
    title: 'Module 4: Templates, Exception Handling & Standard Template Library (STL)',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://www.youtube.com/watch?v=z9bZufPHFLU',
    videoId: 'z9bZufPHFLU',
    isPlaylist: false,
    duration: '42:15',
    description: 'Function and class templates, try-catch exception handling, vector, list, map in STL.',
    tags: ['OOP', 'Mod 4', 'STL', 'Templates'],
    customThumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-05T13:00:00Z',
  },
  {
    id: 'yt-evs-master',
    subjectId: 'sub-evs',
    moduleId: 'mod-evs-1',
    title: 'Environmental Science: Ecosystems, Pollution Control & Green Audits',
    channelName: 'Sustainable Engineering Hub',
    youtubeUrl: 'https://www.youtube.com/watch?v=de9vwMGgTvg',
    videoId: 'de9vwMGgTvg',
    isPlaylist: true,
    duration: 'Full Playlist (10 Videos)',
    description: 'Ecosystems, waste management, climate change mitigation, EIA reports, and environmental laws.',
    tags: ['EVS', '316U06C204', 'Ecosystems', 'Pollution Control'],
    customThumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-05T10:00:00Z',
  },
  {
    id: 'yt-evs-mod2',
    subjectId: 'sub-evs',
    moduleId: 'mod-evs-2',
    title: 'Module 2: Pollution Control & Hazardous Waste Management',
    channelName: 'Sustainable Engineering Hub',
    youtubeUrl: 'https://www.youtube.com/watch?v=9_H8XWz9J_g',
    videoId: '9_H8XWz9J_g',
    isPlaylist: false,
    duration: '29:40',
    description: 'Air and water pollution control technologies, municipal solid waste and e-waste management.',
    tags: ['EVS', 'Mod 2', 'Pollution Control'],
    customThumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-05T11:00:00Z',
  },
];

export const INITIAL_FLASHCARD_DECKS: FlashcardDeck[] = [
  {
    id: 'deck-math1-core',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-5',
    title: 'Applied Mathematics – I: High-Yield Formulas',
    description: 'Essential De Moivre formulas, Euler homogeneous theorems, and rank reduction rules.',
    createdAt: '2025-01-15T00:00:00Z',
    cards: [
      {
        id: 'card-m1',
        deckId: 'deck-math1-core',
        front: 'State De Moivre’s Theorem for integer indices n.',
        back: 'For any real number θ and integer n:\n(cos θ + i sin θ)^n = cos(nθ) + i sin(nθ).',
        tags: ['Maths1', 'DeMoivre', 'Formulas'],
        difficulty: 'easy',
      },
      {
        id: 'card-m2',
        deckId: 'deck-math1-core',
        front: 'State Euler’s Theorem for a homogeneous function u = f(x, y) of degree n.',
        back: 'x(∂u/∂x) + y(∂u/∂y) = n · u\nand\nx²(∂²u/∂x²) + 2xy(∂²u/∂x∂y) + y²(∂²u/∂y²) = n(n - 1) · u.',
        tags: ['Maths1', 'Euler', 'PartialDiff'],
        difficulty: 'medium',
      },
      {
        id: 'card-m3',
        deckId: 'deck-math1-core',
        front: 'When is a square matrix A considered Unitary?',
        back: 'A matrix A is unitary if (A^θ) · A = A · (A^θ) = I, where A^θ is the conjugate transpose of A.',
        tags: ['Maths1', 'Matrices', 'Unitary'],
        difficulty: 'medium',
      }
    ]
  },
  {
    id: 'deck-bee-core',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-1',
    title: 'Basic Electrical Engineering: Network Theorems',
    description: 'Thevenin, Norton, and Maximum Power Transfer conditions for circuit analysis.',
    createdAt: '2025-01-20T00:00:00Z',
    cards: [
      {
        id: 'card-b1',
        deckId: 'deck-bee-core',
        front: 'State Maximum Power Transfer Theorem for DC resistive networks.',
        back: 'Maximum power is transferred from a source to a load resistance when RL = Rth (load resistance equals Thevenin equivalent resistance). Under this condition, Pmax = (Vth²)/(4 · Rth).',
        tags: ['BEE', 'MaxPower', 'Theorems'],
        difficulty: 'easy',
      },
      {
        id: 'card-b2',
        deckId: 'deck-bee-core',
        front: 'What is the relationship between Thevenin voltage (Vth), Norton current (IN), and equivalent resistance (Rth)?',
        back: 'Vth = IN · Rth   or   IN = Vth / Rth, where Rth is identical in both models.',
        tags: ['BEE', 'Thevenin', 'Norton'],
        difficulty: 'easy',
      }
    ]
  }
];

export const INITIAL_DIAGRAMS: MermaidDiagram[] = [
  {
    id: 'diag-bee-theorems',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-1',
    title: 'DC Network Theorem Decision Flowchart',
    diagramType: 'flowchart',
    explanation: 'Step-by-step decision tree for applying Thevenin, Norton, or Superposition theorems to solve circuit questions.',
    mermaidCode: `graph TD
    Start([Given DC Circuit]) --> CheckSources{Multiple Independent Sources?}
    CheckSources -->|Yes & Single Linear Response Needed| Super[Apply Superposition Theorem: Activate 1 Source at a time]
    CheckSources -->|Variable Load Resistor RL Present| ThevDec{Analyze via Thevenin or Norton?}
    
    ThevDec -->|Voltage Source Model| Thevenin[1. Remove RL and find Open Circuit Vth\\n2. Deactivate Sources to find Rth\\n3. IL = Vth / Rth + RL]
    ThevDec -->|Current Source Model| Norton[1. Short Terminals A-B to find IN\\n2. Find Norton Resistance RN = Rth\\n3. IL = IN * RN / RN + RL]
    
    Thevenin --> PowerCheck{Max Power Required?}
    Norton --> PowerCheck
    PowerCheck -->|RL = Rth| MaxP[Pmax = Vth^2 / 4Rth]
    PowerCheck -->|Standard Load| Done([Calculate Load Voltage & Current])`,
    createdAt: '2025-01-20T00:00:00Z',
  }
];
