import { Subject, Module, AcademicResource, YouTubeResource, FlashcardDeck, MermaidDiagram } from './types';

export const INITIAL_SUBJECTS: Subject[] = [
  // --- SEMESTER I ---
  {
    id: 'sub-math1',
    semester: 1,
    code: '316U06C101',
    name: 'Applied Mathematics – I',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 4,
    theoryCredits: 3,
    tutorialCredits: 1,
    practicalCredits: 0,
    hasLab: false,
    description: 'Rank of matrix, linear systems, partial differentiation, Maxima-Minima, Jacobians, Euler theorem, ordinary differential equations, complex numbers, and hyperbolic functions.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
    iconName: 'Calculator',
  },
  {
    id: 'sub-phy',
    semester: 1,
    code: '316U06C102',
    name: 'Engineering Physics',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 2,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Thin film interference, Newton’s rings, diffraction grating, lasers, optical fibers, quantum mechanics wavefunctions, semiconductors, and electromagnetism.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=600&auto=format&fit=crop&q=80',
    iconName: 'Atom',
  },
  {
    id: 'sub-chem',
    semester: 1,
    code: '316U06C103',
    name: 'Engineering Chemistry',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 2,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Industrial water hardness & treatment (BOD/COD), 12 principles of green chemistry, synthetic organic name reactions, rearrangements, electrochemistry, and corrosion control.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    iconName: 'FlaskConical',
  },
  {
    id: 'sub-bee',
    semester: 1,
    code: '316U06C104',
    name: 'Basic Electrical Engineering',
    category: 'ES',
    scheme: 'REV_2025',
    credits: 2,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'DC network theorems (Thevenin, Norton, Superposition, Max Power), 1-phase AC RLC circuits, resonance, 3-phase star/delta power, transformers, DC motors, and induction motors.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    iconName: 'Zap',
  },
  {
    id: 'sub-ed',
    semester: 1,
    code: '316U06C105',
    name: 'Engineering Drawing',
    category: 'ES',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 2,
    tutorialCredits: 1,
    practicalCredits: 0,
    hasLab: false,
    description: 'First angle orthographic projections, full sectional views, projection of points, lines, planes, regular solids, lateral surface development, and isometric drawings.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    iconName: 'Compass',
  },
  {
    id: 'sub-bio',
    semester: 1,
    code: '316U06C106',
    name: 'Biology for Engineers',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 2,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Biomolecules, enzyme kinetics, cell biology, DNA/RNA, bioinformatics, bioprocess fermentors, biosensors, biomedical instrumentation (ECG/EEG/MRI), systems biology, and biomechanics.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&auto=format&fit=crop&q=80',
    iconName: 'Dna',
  },
  {
    id: 'sub-spm',
    semester: 1,
    code: '316U06C107',
    name: 'Structured Programming Methodology',
    category: 'ES',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 1,
    hasLab: true,
    description: 'Problem solving algorithms, control flow constructs, 1D/2D arrays, string operations, modular functions, recursion, structures, unions, pointers, and memory handling.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    iconName: 'Code',
  },

  // --- SEMESTER II (Computer Engineering - SVU R-2025 v3.0) ---
  {
    id: 'sub-math2',
    semester: 2,
    code: '316U06C201',
    name: 'Applied Mathematics – II',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 4,
    theoryCredits: 3,
    tutorialCredits: 1,
    practicalCredits: 0,
    hasLab: false,
    description: 'Eigenvalues and eigenvectors, Cayley-Hamilton theorem, similarity and diagonalization, successive differentiation (Leibnitz theorem), expansion of functions (Taylor/Maclaurin), Beta and Gamma functions, DUIS, rectification, and multiple integration (double & triple integrals).',
    thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    iconName: 'Calculator',
  },
  {
    id: 'sub-ascap',
    semester: 2,
    code: '316U06E211',
    name: 'Applied Science for Computer & Allied Programs',
    category: 'BS',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 3,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Physics and chemistry applied foundations for computing, quantum computing fundamentals, semiconductor device physics, photonic materials, and computational materials science.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop&q=80',
    iconName: 'Microscope',
  },
  {
    id: 'sub-dld',
    semester: 2,
    code: '316U06C203',
    name: 'Digital Logic Design',
    category: 'ES',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 3,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Number systems, Boolean algebra, logic gate minimization (K-Maps, Quine-McCluskey), combinational circuits (adders, multiplexers, decoders), sequential circuits (flip-flops, registers, counters), and FSM design.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    iconName: 'Cpu',
  },
  {
    id: 'sub-evs',
    semester: 2,
    code: '316U06C204',
    name: 'Environmental Science',
    category: 'HS',
    scheme: 'REV_2025',
    credits: 2,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 0,
    hasLab: false,
    description: 'Ecosystems, natural resources, biodiversity conservation, air/water/soil pollution control, climate change, renewable energy, waste management, and environmental legislation.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80',
    iconName: 'Leaf',
  },
  {
    id: 'sub-oop',
    semester: 2,
    code: '316U06C205',
    name: 'Object-Oriented Programming Methodology',
    category: 'ES',
    scheme: 'REV_2025',
    credits: 3,
    theoryCredits: 2,
    tutorialCredits: 0,
    practicalCredits: 1,
    hasLab: true,
    description: 'Classes, data abstraction, encapsulation, constructors/destructors, operator overloading, inheritance hierarchies, runtime polymorphism, virtual functions, templates, and STL.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    iconName: 'Code',
  }
];

export const INITIAL_MODULES: Module[] = [
  // --- Applied Mathematics – I (316U06C101) ---
  {
    id: 'mod-m1-1',
    subjectId: 'sub-math1',
    moduleNumber: 1,
    title: 'Rank of Matrix and System of Equations',
    description: 'Hermitian, skew-Hermitian, unitary and orthogonal matrices. Rank using row echelon/normal forms, consistency of linear equations, Gauss-Seidel and Jacobi iteration methods.',
    topics: ['Hermitian & Unitary Matrices', 'Row Echelon & Normal Form', 'Linear Systems Consistency', 'Gauss-Seidel & Jacobi Iterations'],
    weightageMarks: 18,
  },
  {
    id: 'mod-m1-2',
    subjectId: 'sub-math1',
    moduleNumber: 2,
    title: 'Partial Differentiation and Application',
    description: 'Partial derivatives of first and higher orders, composite functions, Maxima and Minima of two independent variables, and Jacobians of two and three variables.',
    topics: ['Higher Order Partial Derivatives', 'Composite Function Differentiation', 'Maxima & Minima of 2 Variables', 'Jacobians'],
    weightageMarks: 18,
  },
  {
    id: 'mod-m1-3',
    subjectId: 'sub-math1',
    moduleNumber: 3,
    title: 'Homogeneous Functions & Euler’s Theorem',
    description: 'Euler’s theorem on homogeneous functions with two and three independent variables, and analytical deductions/corollaries.',
    topics: ['Euler’s Theorem on Homogeneous Functions', 'Corollaries & Deductions', 'Multivariable Homogeneity'],
    weightageMarks: 14,
  },
  {
    id: 'mod-m1-4',
    subjectId: 'sub-math1',
    moduleNumber: 4,
    title: 'Linear Differential Equations of First and Higher Order',
    description: 'Exact differential equations, integrating factors, higher order linear ODEs with constant coefficients, complementary functions, particular integrals, and variation of parameters.',
    topics: ['Exact Differential Equations', 'Integrating Factors', 'Higher Order Linear ODEs', 'Particular Integrals (CF & PI)', 'Variation of Parameters'],
    weightageMarks: 20,
  },
  {
    id: 'mod-m1-5',
    subjectId: 'sub-math1',
    moduleNumber: 5,
    title: 'Complex Numbers, Hyperbolic Functions & Logarithms',
    description: 'De Moivre’s theorem, powers and roots of complex numbers, circular and hyperbolic functions, inverse functions, and separation into real and imaginary parts.',
    topics: ['De Moivre’s Theorem', 'Roots of Complex Numbers', 'Hyperbolic & Inverse Hyperbolic Functions', 'Logarithm of Complex Numbers'],
    weightageMarks: 18,
  },

  // --- Engineering Physics (316U06C102) ---
  {
    id: 'mod-phy-1',
    subjectId: 'sub-phy',
    moduleNumber: 1,
    title: 'Wave Optics (Interference & Diffraction)',
    description: 'Interference in thin parallel films, wedge-shaped films, Newton’s Rings, Fraunhofer diffraction through grating, and resolving power.',
    topics: ['Thin Parallel Film Interference', 'Wedge-Shaped Films & Newton’s Rings', 'Diffraction Grating', 'Resolving Power'],
    weightageMarks: 16,
  },
  {
    id: 'mod-phy-2',
    subjectId: 'sub-phy',
    moduleNumber: 2,
    title: 'Photonics (Lasers & Optical Fibers)',
    description: 'Laser principles, Einstein coefficients, threshold condition, optical fiber total internal reflection, step index numerical aperture derivation, and fiber losses.',
    topics: ['Einstein Coefficients', 'Laser Threshold Condition', 'Optical Fiber Step Index', 'Numerical Aperture Derivation', 'Attenuation Losses'],
    weightageMarks: 16,
  },
  {
    id: 'mod-phy-3',
    subjectId: 'sub-phy',
    moduleNumber: 3,
    title: 'Quantum Mechanics – I',
    description: 'De-Broglie hypothesis, Heisenberg uncertainty principle, wavefunctions, probabilistic interpretation, and normalization condition.',
    topics: ['De-Broglie Matter Waves', 'Heisenberg Uncertainty Principle', 'Wavefunction Properties', 'Normalization Condition'],
    weightageMarks: 14,
  },
  {
    id: 'mod-phy-4',
    subjectId: 'sub-phy',
    moduleNumber: 4,
    title: 'Semiconductors & Electromagnetism',
    description: 'Intrinsic/extrinsic semiconductors, drift and diffusion currents, Fermi level position, Del operator, gradient, divergence, curl, and fundamental EM theorems.',
    topics: ['Mobility & Conductivity', 'Drift & Diffusion Current', 'Fermi-Dirac Distribution', 'Del, Gradient, Divergence, Curl'],
    weightageMarks: 16,
  },

  // --- Engineering Chemistry (316U06C103) ---
  {
    id: 'mod-ch-1',
    subjectId: 'sub-chem',
    moduleNumber: 1,
    title: 'Industrial Water Treatment & Pollution',
    description: 'Types of hardness, EDTA determination, lime-soda, zeolite, ion-exchange processes, BOD, COD, and industrial wastewater treatment.',
    topics: ['Water Hardness & EDTA Titration', 'Zeolite & Ion-Exchange Methods', 'BOD & COD Parameters', 'Industrial Effluent Treatment'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ch-2',
    subjectId: 'sub-chem',
    moduleNumber: 2,
    title: 'Green Chemistry for Sustainable Engineering',
    description: 'Twelve principles of green chemistry (Anastas & Warner), green solvents (supercritical CO2, ionic liquids), atom economy, microwave and ultrasound synthesis.',
    topics: ['Twelve Principles of Green Chemistry', 'Green Solvents & Supercritical Fluids', 'Atom Economy & Environmental Metrics', 'Microwave-Assisted Synthesis'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ch-3',
    subjectId: 'sub-chem',
    moduleNumber: 3,
    title: 'Synthetic Organic & Rearrangement Reactions',
    description: 'Aldol condensation, Baeyer-Villiger oxidation, Dakin reaction, Haloform, Sharpless epoxidation, Benzil-Benzilic, Pinacole-Pinacolone, and Fries rearrangements.',
    topics: ['Aldol & Baeyer-Villiger Reactions', 'Haloform & Sharpless Epoxidation', 'Benzilic Acid & Pinacolone Rearrangements', 'Fries Rearrangement'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ch-4',
    subjectId: 'sub-chem',
    moduleNumber: 4,
    title: 'Electrochemistry & Corrosion Fundamentals',
    description: 'Nernst equation, cell potentials, mechanisms of dry/wet corrosion, cathodic/anodic protection, corrosion inhibitors, and protective coatings.',
    topics: ['Nernst Equation & Cell Potentials', 'Corrosion Mechanisms & Types', 'Cathodic & Anodic Protection', 'Inhibitors & Protective Coatings'],
    weightageMarks: 16,
  },

  // --- Basic Electrical Engineering (316U06C104) ---
  {
    id: 'mod-bee-1',
    subjectId: 'sub-bee',
    moduleNumber: 1,
    title: 'DC Circuits & Network Theorems',
    description: 'Kirchhoff’s laws, source transformation, mesh/nodal analysis, Superposition, Thevenin’s, Norton’s, and Maximum Power Transfer theorems.',
    topics: ['Kirchhoff’s Laws & Source Transformation', 'Mesh & Nodal Analysis', 'Thevenin & Norton Theorems', 'Maximum Power Transfer'],
    weightageMarks: 20,
  },
  {
    id: 'mod-bee-2',
    subjectId: 'sub-bee',
    moduleNumber: 2,
    title: 'Single Phase AC Circuits & Resonance',
    description: 'Sinusoidal quantities, RMS, average value, phasor diagrams, RLC series/parallel circuits, power triangle (P, Q, S), power factor improvement, and resonance Q-factor.',
    topics: ['Phasor Representation & RMS Values', 'Series & Parallel RLC Circuits', 'Power Factor & Power Triangle', 'Resonance & Quality Factor'],
    weightageMarks: 18,
  },
  {
    id: 'mod-bee-3',
    subjectId: 'sub-bee',
    moduleNumber: 3,
    title: 'Three Phase AC Circuits',
    description: 'Balanced 3-phase circuits, star and delta connections, line/phase voltage-current relations, and 3-phase power measurement using two-wattmeter method.',
    topics: ['Star & Delta Connections', 'Line vs Phase Relations', 'Two-Wattmeter Power Measurement'],
    weightageMarks: 14,
  },
  {
    id: 'mod-bee-4',
    subjectId: 'sub-bee',
    moduleNumber: 4,
    title: 'Introduction to Electrical Machines',
    description: 'Single phase transformer construction, EMF equation, losses and efficiency, DC motor torque-speed characteristics, and 1-phase induction motors.',
    topics: ['Transformer Working & EMF Equation', 'Transformer Losses & Efficiency', 'DC Motor Characteristics', 'Single Phase Induction Motor'],
    weightageMarks: 14,
  },

  // --- Engineering Drawing (316U06C105) ---
  {
    id: 'mod-ed-1',
    subjectId: 'sub-ed',
    moduleNumber: 1,
    title: 'Orthographic Projections & Sectional Views',
    description: 'First angle orthographic projections of machine parts, dimensioning standards, scales, and full sectional orthographic views.',
    topics: ['First Angle Projection Principles', 'Multi-View Orthographic Layouts', 'Full Sectional Views'],
    weightageMarks: 18,
  },
  {
    id: 'mod-ed-2',
    subjectId: 'sub-ed',
    moduleNumber: 2,
    title: 'Projection of Points, Lines and Planes',
    description: 'Projections of lines inclined to both reference planes (1st quadrant), projections of regular geometric planes (triangular, square, hexagonal, circular).',
    topics: ['Lines Inclined to Both Planes', 'True Length & Apparent Angles', 'Projections of Regular Planes'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ed-3',
    subjectId: 'sub-ed',
    moduleNumber: 3,
    title: 'Projection of Solids',
    description: 'Projections of prisms, pyramids, cylinders, and cones with axis inclined to one reference plane.',
    topics: ['Prisms & Pyramids Projections', 'Cylinders & Cones Projections', 'Axis Inclination Principles'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ed-4',
    subjectId: 'sub-ed',
    moduleNumber: 4,
    title: 'Section and Lateral Development of Solids',
    description: 'Sectional views of solids cut by inclined cutting planes, and lateral surface development of prisms, cylinders, and cones.',
    topics: ['Section Planes & True Shape of Section', 'Lateral Surface Development', 'Radial Line & Parallel Line Development'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ed-5',
    subjectId: 'sub-ed',
    moduleNumber: 5,
    title: 'Isometric View & 3D Drafting',
    description: 'Isometric scale, isometric views and projections of composite machine solids.',
    topics: ['Isometric Projection vs View', 'Isometric Drafting of Machine Components'],
    weightageMarks: 14,
  },

  // --- Biology for Engineers (316U06C106) ---
  {
    id: 'mod-bio-1',
    subjectId: 'sub-bio',
    moduleNumber: 1,
    title: 'Biomolecules and Enzymes',
    description: 'Proteins, carbohydrates, lipids, nucleic acids, enzyme kinetics, cofactors, and industrial biocatalytic applications.',
    topics: ['Biomolecule Classifications', 'Enzyme Kinetics & Cofactors', 'Industrial Biocatalysis'],
    weightageMarks: 16,
  },
  {
    id: 'mod-bio-2',
    subjectId: 'sub-bio',
    moduleNumber: 2,
    title: 'Cell Biology & Bioinformatics',
    description: 'Prokaryotic/eukaryotic cells, cell cycle, DNA replication, transcription, translation, and bioinformatics sequence analysis tools.',
    topics: ['Cell Cycle & Division', 'Central Dogma of Molecular Biology', 'Bioinformatics Sequence Tools'],
    weightageMarks: 16,
  },
  {
    id: 'mod-bio-3',
    subjectId: 'sub-bio',
    moduleNumber: 3,
    title: 'Bioprocess Engineering & Fermentors',
    description: 'Fermentor vessel design, upstream/downstream processing, Monod growth kinetics, and fermentation of antibiotics/acids.',
    topics: ['Fermentor Design & Sensors', 'Upstream & Downstream Processing', 'Monod Growth Kinetics'],
    weightageMarks: 16,
  },
  {
    id: 'mod-bio-4',
    subjectId: 'sub-bio',
    moduleNumber: 4,
    title: 'Biosensors & Biomedical Instrumentation',
    description: 'Biosensor transducers, optical/pressure/chemical sensors, heart physiology, EEG, ECG, Ultrasound, MRI, and Tomography.',
    topics: ['Biosensor Transduction Principles', 'ECG, EEG & Physiological Monitoring', 'MRI & Tomographic Imaging'],
    weightageMarks: 16,
  },
  {
    id: 'mod-bio-5',
    subjectId: 'sub-bio',
    moduleNumber: 5,
    title: 'Systems Biology & Biomechanics',
    description: 'Metabolic pathway dynamics, musculoskeletal/cardiovascular mechanics, biocompatible materials, implants, and tissue engineering.',
    topics: ['Metabolic Network Modeling', 'Musculoskeletal & Blood Flow Models', 'Biomaterial Biocompatibility', 'Tissue Engineering'],
    weightageMarks: 16,
  },

  // --- Structured Programming Methodology (316U06C107) ---
  {
    id: 'mod-spm-1',
    subjectId: 'sub-spm',
    moduleNumber: 1,
    title: 'Algorithms & Structured Programming Basics',
    description: 'Problem definition, algorithms, flowcharts, pseudocode, SDLC, data types, identifiers, operator precedence, and type conversions.',
    topics: ['Algorithms & Flowchart Logic', 'Data Types & Variables', 'Operators & Precedence Rules', 'Type Conversion'],
    weightageMarks: 16,
  },
  {
    id: 'mod-spm-2',
    subjectId: 'sub-spm',
    moduleNumber: 2,
    title: 'Program Control Structures',
    description: 'Two-way and multiway selection (if-else, switch-case), looping constructs (for, while, do-while), flags, and code readability.',
    topics: ['Selection & Branching (if-else, switch)', 'Iteration & Loops (for, while)', 'Flag Concepts & Best Practices'],
    weightageMarks: 16,
  },
  {
    id: 'mod-spm-3',
    subjectId: 'sub-spm',
    moduleNumber: 3,
    title: 'Arrays & String Processing',
    description: '1D and multidimensional array operations, character arrays, string declarations, and string processing functions from scratch.',
    topics: ['1D & 2D Array Operations', 'String Handling from Scratch', 'Memory Layout of Arrays'],
    weightageMarks: 18,
  },
  {
    id: 'mod-spm-4',
    subjectId: 'sub-spm',
    moduleNumber: 4,
    title: 'Functions, Structures & Pointers',
    description: 'User-defined functions, pass by value, recursion, structures, unions, pointer declaration, pointer arithmetic, pass by reference, and dynamic memory.',
    topics: ['Modular Functions & Recursion', 'Structures & Unions', 'Pointers & Memory Addresses', 'Pass by Reference'],
    weightageMarks: 20,
  },

  // --- SEMESTER II MODULES ---
  // --- Applied Mathematics – II (316U06C201) ---
  {
    id: 'mod-m2-1',
    subjectId: 'sub-math2',
    moduleNumber: 1,
    title: 'Eigenvalues and Eigenvectors',
    description: 'Characteristic equation, Cayley-Hamilton theorem and applications, eigenvalues and eigenvectors with properties, similarity of matrices, diagonalization, functions of a square matrix, PCA, SVD, and derogatory/non-derogatory matrices.',
    topics: ['Cayley-Hamilton Theorem & Applications', 'Eigenvalues & Eigenvectors Properties', 'Similarity & Diagonalization of Matrices', 'Functions of a Square Matrix', 'PCA & Singular Value Decomposition (SVD)', 'Derogatory & Non-Derogatory Matrices'],
    weightageMarks: 20,
  },
  {
    id: 'mod-m2-2',
    subjectId: 'sub-math2',
    moduleNumber: 2,
    title: 'Successive Differentiation, Expansion of Functions',
    description: 'Successive differentiation, nth derivative of standard functions, Leibnitz’s theorem, Taylor’s theorem & series, Maclaurin’s series, expansion of hyperbolic & logarithmic functions, indeterminate forms, and L’Hospital Rule.',
    topics: ['nth Derivative of Standard Functions', 'Leibnitz’s Theorem', 'Taylor’s & Maclaurin’s Series Expansion', 'Indeterminate Forms & L’Hospital Rule'],
    weightageMarks: 16,
  },
  {
    id: 'mod-m2-3',
    subjectId: 'sub-math2',
    moduleNumber: 3,
    title: 'Integration : Review and Some New Techniques',
    description: 'Beta and Gamma functions with standard properties, Differentiation Under Integral Sign (DUIS) with constant limits and variable limits of integration.',
    topics: ['Beta & Gamma Functions with Properties', 'DUIS with Constant Limits', 'DUIS with Variable Limits'],
    weightageMarks: 16,
  },
  {
    id: 'mod-m2-4',
    subjectId: 'sub-math2',
    moduleNumber: 4,
    title: 'Rectification',
    description: 'Rectification and arc length computation of plane curves in Cartesian form, parametric form, and polar coordinate forms.',
    topics: ['Rectification in Cartesian Form', 'Rectification in Parametric Form', 'Rectification in Polar Form'],
    weightageMarks: 14,
  },
  {
    id: 'mod-m2-5',
    subjectId: 'sub-math2',
    moduleNumber: 5,
    title: 'Multiple Integration and their Applications',
    description: 'Double integration over given regions, change of order of integration, change to polar form, triple integration in Cartesian, cylindrical and spherical coordinates, area and volume applications, and mass of lamina.',
    topics: ['Double Integration & Evaluation Over Regions', 'Change of Order of Integration & Polar Form', 'Triple Integration (Cartesian, Cylindrical, Spherical)', 'Area & Volume Applications', 'Mass of Lamina'],
    weightageMarks: 20,
  },

  // --- Applied Science for Computer & Allied Programs / ASCT (316U06E211) ---
  {
    id: 'mod-ascap-1',
    subjectId: 'sub-ascap',
    moduleNumber: 1,
    title: 'Quantum Physics Fundamentals for Computing',
    description: 'Quantum state postulates, wave-particle duality, Schrödinger equation, quantum tunneling, and qubit physics for quantum computing systems.',
    topics: ['Wave-Particle Duality & Schrödinger Equation', 'Quantum Tunneling & Potential Wells', 'Qubits & Quantum Computing Foundations'],
    weightageMarks: 18,
  },
  {
    id: 'mod-ascap-2',
    subjectId: 'sub-ascap',
    moduleNumber: 2,
    title: 'Semiconductor Device Physics & Band Theory',
    description: 'Kronig-Penney model, energy bands in solids, Fermi energy level, carrier transport, drift/diffusion currents, and pn-junction diodes.',
    topics: ['Energy Bands & Kronig-Penney Model', 'Direct & Indirect Bandgap Semiconductors', 'Fermi Level & Carrier Transport', 'p-n Junction Physics'],
    weightageMarks: 18,
  },
  {
    id: 'mod-ascap-3',
    subjectId: 'sub-ascap',
    moduleNumber: 3,
    title: 'Optoelectronics, Photonic Materials & Lasers',
    description: 'Stimulated emission, semiconductor laser diodes, photodetectors, optical fiber communication principles, and photonic interconnects in computers.',
    topics: ['Lasers & Stimulated Emission', 'Semiconductor Laser Diodes & LEDs', 'Photodetectors & Optocouplers', 'Optical Fiber Transmission'],
    weightageMarks: 16,
  },
  {
    id: 'mod-ascap-4',
    subjectId: 'sub-ascap',
    moduleNumber: 4,
    title: 'Computational Materials Science & Nanomaterials',
    description: 'Carbon nanotubes, graphene, quantum dots, 2D nanomaterials for next-gen processors, and magnetic storage physics.',
    topics: ['Carbon Nanotubes & Graphene', 'Quantum Dots & 2D Materials', 'Magnetic Materials & Storage Physics'],
    weightageMarks: 16,
  },

  // --- Digital Logic Design (316U06C203) ---
  {
    id: 'mod-dld-1',
    subjectId: 'sub-dld',
    moduleNumber: 1,
    title: 'Number Systems & Boolean Algebra',
    description: 'Binary, octal, hexadecimal number systems, signed binary representations, 1s and 2s complements, Boolean algebra postulates, and logic gate truth tables.',
    topics: ['Number Systems & Radix Conversions', '1s & 2s Complement Arithmetic', 'Boolean Postulates & Theorems', 'Universal Logic Gates (NAND & NOR)'],
    weightageMarks: 16,
  },
  {
    id: 'mod-dld-2',
    subjectId: 'sub-dld',
    moduleNumber: 2,
    title: 'Logic Minimization & Combinational Circuits',
    description: 'Karnaugh Maps (K-Maps up to 5 variables), POS & SOP simplification, Quine-McCluskey tabulation, half/full adders, subtractors, multiplexers, and decoders.',
    topics: ['K-Map Minimization (2 to 5 Variables)', 'Quine-McCluskey (Tabular) Method', 'Adders, Subtractors & Look-Ahead Carry', 'Multiplexers, Demultiplexers & Decoders'],
    weightageMarks: 20,
  },
  {
    id: 'mod-dld-3',
    subjectId: 'sub-dld',
    moduleNumber: 3,
    title: 'Sequential Logic Circuits & Flip-Flops',
    description: 'Latches vs flip-flops, SR, JK, Master-Slave JK, D, and T flip-flops, excitation tables, race-around condition, and flip-flop conversions.',
    topics: ['SR, JK, D & T Flip-Flops', 'Master-Slave JK & Race-Around Condition', 'Flip-Flop Conversion & Excitation Tables'],
    weightageMarks: 18,
  },
  {
    id: 'mod-dld-4',
    subjectId: 'sub-dld',
    moduleNumber: 4,
    title: 'Registers, Counters & Finite State Machines (FSM)',
    description: 'Shift registers (SISO, SIPO, PISO, PIPO), universal shift registers, asynchronous ripple counters, synchronous counters, up/down counters, and Mealy/Moore state machines.',
    topics: ['Shift Registers & Universal Shift Register', 'Asynchronous & Synchronous Binary Counters', 'Ring & Johnson Counters', 'Mealy & Moore State Machines'],
    weightageMarks: 20,
  },
  {
    id: 'mod-dld-5',
    subjectId: 'sub-dld',
    moduleNumber: 5,
    title: 'Programmable Logic & Hardware Description',
    description: 'ROM, PROM, PLA (Programmable Logic Array), PAL (Programmable Array Logic), FPGA basics, and introductory digital hardware modeling.',
    topics: ['ROM, PROM, PLA & PAL Architecture', 'FPGA & CPLD Architectures', 'Digital Hardware Modeling Basics'],
    weightageMarks: 16,
  },

  // --- Environmental Science (316U06C204) ---
  {
    id: 'mod-evs-1',
    subjectId: 'sub-evs',
    moduleNumber: 1,
    title: 'Ecosystems & Biodiversity Conservation',
    description: 'Structure and function of ecosystems, energy flow, food chains, biodiversity hotspots, and conservation strategies.',
    topics: ['Ecosystem Dynamics & Food Webs', 'Biodiversity Hotspots & Threats', 'In-situ & Ex-situ Conservation'],
    weightageMarks: 16,
  },
  {
    id: 'mod-evs-2',
    subjectId: 'sub-evs',
    moduleNumber: 2,
    title: 'Pollution Control & Waste Management',
    description: 'Air, water, soil, noise pollution, control technologies, solid waste management, e-waste handling, and circular economy.',
    topics: ['Air & Water Pollution Technologies', 'Solid & Hazardous Waste Management', 'E-Waste Recycling & Circular Economy'],
    weightageMarks: 18,
  },
  {
    id: 'mod-evs-3',
    subjectId: 'sub-evs',
    moduleNumber: 3,
    title: 'Climate Change & Sustainable Energy',
    description: 'Greenhouse effect, global warming, carbon footprint reduction, solar, wind, and green hydrogen energy systems.',
    topics: ['Global Warming & Carbon Footprints', 'Solar & Wind Energy Systems', 'Green Hydrogen & Clean Fuels'],
    weightageMarks: 16,
  },
  {
    id: 'mod-evs-4',
    subjectId: 'sub-evs',
    moduleNumber: 4,
    title: 'Environmental Legislation & Green Audits',
    description: 'Environmental protection acts, ISO 14001, Environmental Impact Assessment (EIA), and sustainable engineering practices.',
    topics: ['Environmental Protection Act (EPA)', 'Environmental Impact Assessment (EIA)', 'Green Building & Carbon Offsets'],
    weightageMarks: 16,
  },

  // --- Object-Oriented Programming Methodology (316U06C205) ---
  {
    id: 'mod-oop-1',
    subjectId: 'sub-oop',
    moduleNumber: 1,
    title: 'Classes, Objects & Data Encapsulation',
    description: 'Principles of object-oriented design, class declarations, object instantiation, access specifiers, static members, and friend functions.',
    topics: ['Class Declarations & Member Functions', 'Access Specifiers (public/private/protected)', 'Static Members & Friend Functions'],
    weightageMarks: 16,
  },
  {
    id: 'mod-oop-2',
    subjectId: 'sub-oop',
    moduleNumber: 2,
    title: 'Constructors, Destructors & Operator Overloading',
    description: 'Default, parameterized, and copy constructors, destructor cleanup, unary and binary operator overloading, and type conversion.',
    topics: ['Constructors (Default, Parameterized, Copy)', 'Destructor Resource Management', 'Unary & Binary Operator Overloading'],
    weightageMarks: 18,
  },
  {
    id: 'mod-oop-3',
    subjectId: 'sub-oop',
    moduleNumber: 3,
    title: 'Inheritance Hierarchies & Polymorphism',
    description: 'Single, multiple, multilevel, hierarchical, and hybrid inheritance, virtual base classes, virtual functions, abstract classes, and runtime polymorphism.',
    topics: ['Inheritance Types & Base Initialization', 'Virtual Functions & Runtime Binding', 'Abstract Classes & Pure Virtual Functions'],
    weightageMarks: 20,
  },
  {
    id: 'mod-oop-4',
    subjectId: 'sub-oop',
    moduleNumber: 4,
    title: 'Templates, Exceptions & STL Containers',
    description: 'Function and class templates, try-catch exception handling, standard template library (vector, list, map), and iterators.',
    topics: ['Function & Class Templates', 'Exception Handling Mechanisms', 'STL Vectors, Maps & Iterators'],
    weightageMarks: 18,
  }
];

export const INITIAL_RESOURCES: AcademicResource[] = [
  // --- Applied Mathematics – I Module-Wise Lecture Notes & Parts ---
  {
    id: 'res-math1-mod1-p1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-1',
    title: 'Rank of Matrix and System of Equations (Part 1)',
    type: 'notes',
    filePath: '/sample-resources/maths1_matrix_rank_p1.pdf',
    fileName: 'AM1_Mod1_Matrix_Rank_Part1.pdf',
    fileSizeBytes: 520000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1840,
    tags: ['Sem1', '316U06C101', 'Rank of Matrix', 'Row Echelon'],
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'res-math1-mod1-p2',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-1',
    title: 'Consistency of Linear Equations & Iterative Methods (Part 2)',
    type: 'notes',
    filePath: '/sample-resources/maths1_matrix_rank_p2.pdf',
    fileName: 'AM1_Mod1_Linear_Systems_Part2.pdf',
    fileSizeBytes: 680000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1520,
    tags: ['Sem1', 'Gauss-Seidel', 'Jacobi Method'],
    createdAt: '2025-01-12T10:00:00Z',
  },
  {
    id: 'res-math1-mod2-p1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation and Application (Part 1)',
    type: 'notes',
    filePath: '/sample-resources/maths1_partial_diff_p1.pdf',
    fileName: 'AM1_Mod2_Partial_Diff_Part1.pdf',
    fileSizeBytes: 559000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2450,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-14T10:00:00Z',
  },
  {
    id: 'res-math1-mod2-p2',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation and Application (Part 2)',
    type: 'notes',
    filePath: '/sample-resources/maths1_partial_diff_p2.pdf',
    fileName: 'AM1_Mod2_Partial_Diff_Part2.pdf',
    fileSizeBytes: 453000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2210,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-15T11:00:00Z',
  },
  {
    id: 'res-math1-mod2-p3',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation and Application (Part 3)',
    type: 'notes',
    filePath: '/sample-resources/maths1_partial_diff_p3.pdf',
    fileName: 'AM1_Mod2_Partial_Diff_Part3.pdf',
    fileSizeBytes: 233000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1980,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-16T12:00:00Z',
  },
  {
    id: 'res-math1-mod2-p4',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation and Application (Part 4)',
    type: 'notes',
    filePath: '/sample-resources/maths1_partial_diff_p4.pdf',
    fileName: 'AM1_Mod2_Partial_Diff_Part4.pdf',
    fileSizeBytes: 293000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2130,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-17T14:00:00Z',
  },
  {
    id: 'res-math1-formula-1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation, Jacobians & Maxima-Minima Quick Formula Sheet',
    type: 'formula_sheet',
    filePath: '/sample-resources/maths1_partial_diff_formulas.pdf',
    fileName: 'Maths1_Partial_Diff_Formula_Sheet.pdf',
    fileSizeBytes: 890000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2980,
    tags: ['Sem1', 'Formula Sheet', 'Jacobians', 'Euler Theorem'],
    createdAt: '2025-01-18T14:30:00Z',
  },
  {
    id: 'res-math1-mod3-p1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-3',
    title: 'Homogeneous Functions & Euler’s Theorem Derivations (Part 1)',
    type: 'notes',
    filePath: '/sample-resources/maths1_euler_p1.pdf',
    fileName: 'AM1_Mod3_Euler_Theorem_Part1.pdf',
    fileSizeBytes: 410000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1650,
    tags: ['Sem1', 'Euler Theorem', 'Homogeneous'],
    createdAt: '2025-01-19T10:00:00Z',
  },
  {
    id: 'res-math1-mod4-p1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-4',
    title: 'Linear Differential Equations of First & Higher Order (Part 1)',
    type: 'notes',
    filePath: '/sample-resources/maths1_ode_p1.pdf',
    fileName: 'AM1_Mod4_Linear_ODEs_Part1.pdf',
    fileSizeBytes: 620000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1890,
    tags: ['Sem1', 'ODEs', 'Particular Integrals'],
    createdAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 'res-math1-mod5-p1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-5',
    title: 'Complex Numbers, Hyperbolic Functions and Logarithm of Complex Number (Part 1)',
    type: 'notes',
    filePath: '/sample-resources/maths1_complex_p1.pdf',
    fileName: 'AM1_Mod5_Complex_Numbers_Part1.pdf',
    fileSizeBytes: 789000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2670,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-22T10:00:00Z',
  },
  {
    id: 'res-math1-mod5-p2',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-5',
    title: 'Complex Numbers, Hyperbolic Functions and Logarithm of Complex Number (Part 2)',
    type: 'notes',
    filePath: '/sample-resources/maths1_complex_p2.pdf',
    fileName: 'AM1_Mod5_Complex_Numbers_Part2.pdf',
    fileSizeBytes: 438000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2410,
    tags: ['Sem1', 'Lecture Notes', 'Official'],
    createdAt: '2025-01-23T11:00:00Z',
  },
  {
    id: 'res-phy-slides-1',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-1',
    title: 'Thin Film Interference & Newton’s Rings Complete Slides',
    type: 'ppt',
    filePath: '/sample-resources/physics_interference_slides.pptx',
    fileName: 'Physics_Module1_Interference_Slides.pptx',
    fileSizeBytes: 4900000,
    fileMime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Department of Physics',
    isVerified: true,
    downloadsCount: 1620,
    tags: ['Sem1', '316U06C102', 'Interference', 'Newton Rings'],
    createdAt: '2025-01-25T11:20:00Z',
  },
  {
    id: 'res-chem-notes-1',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-1',
    title: 'Industrial Water Treatment (EDTA, Zeolite & Ion Exchange) Complete Notes',
    type: 'notes',
    filePath: '/sample-resources/chemistry_water_treatment.pdf',
    fileName: 'Chemistry_Module1_Water_Treatment.pdf',
    fileSizeBytes: 3100000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Department of Chemistry',
    isVerified: true,
    downloadsCount: 2150,
    tags: ['Sem1', '316U06C103', 'Water Treatment', 'Zeolite'],
    createdAt: '2025-01-28T09:15:00Z',
  },
  {
    id: 'res-bee-notes-1',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-1',
    title: 'DC Network Theorems (Thevenin, Norton & Max Power) Solved Problems',
    type: 'notes',
    filePath: '/sample-resources/bee_dc_theorems_solved.pdf',
    fileName: 'BEE_DC_Theorems_Handwritten_Notes.pdf',
    fileSizeBytes: 3400000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Department of Electrical Engineering',
    isVerified: true,
    downloadsCount: 2450,
    tags: ['Sem1', '316U06C104', 'Thevenin', 'Norton', 'DC Circuits'],
    createdAt: '2025-01-22T09:00:00Z',
  },
  {
    id: 'res-ed-notes-1',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-1',
    title: 'Engineering Drawing First Angle Orthographic Projections Step-by-Step Guide',
    type: 'notes',
    filePath: '/sample-resources/ed_orthographic_guide.pdf',
    fileName: 'Engineering_Drawing_Orthographic_Projections.pdf',
    fileSizeBytes: 5200000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Department of Mechanical Engineering',
    isVerified: true,
    downloadsCount: 2890,
    tags: ['Sem1', '316U06C105', 'Orthographic', 'First Angle'],
    createdAt: '2025-01-30T10:00:00Z',
  },
  {
    id: 'res-bio-notes-1',
    subjectId: 'sub-bio',
    moduleId: 'mod-bio-1',
    title: 'Biology for Engineers Biomolecules, Enzyme Kinetics & Biosensors Handbook',
    type: 'notes',
    filePath: '/sample-resources/bio_engineers_handbook.pdf',
    fileName: 'Biology_for_Engineers_Study_Guide.pdf',
    fileSizeBytes: 2900000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Life Sciences',
    isVerified: true,
    downloadsCount: 1980,
    tags: ['Sem1', '316U06C106', 'Biomolecules', 'Biosensors'],
    createdAt: '2025-02-02T12:00:00Z',
  },
  // --- PRACTICE QUESTIONS (MODULE-WISE) ---
  {
    id: 'res-math1-practice-1',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-1',
    title: 'Rank of Matrix, Echelon Form & Linear Systems Solved Practice Questions',
    type: 'practice_ques',
    filePath: '/sample-resources/maths1_matrices_practice.pdf',
    fileName: 'AM1_Mod1_Matrices_Practice_Questions.pdf',
    fileSizeBytes: 1450000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 2240,
    tags: ['Sem1', 'Practice Questions', 'Matrices', 'Rank'],
    createdAt: '2025-02-03T10:00:00Z',
  },
  {
    id: 'res-math1-practice-2',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Partial Differentiation, Jacobians & Maxima-Minima Practice Questions',
    type: 'practice_ques',
    filePath: '/sample-resources/maths1_partial_diff_practice.pdf',
    fileName: 'AM1_Mod2_Partial_Diff_Practice_Questions.pdf',
    fileSizeBytes: 1680000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Faculty of Mathematics',
    isVerified: true,
    downloadsCount: 1980,
    tags: ['Sem1', 'Practice Questions', 'Jacobians', 'Partial Diff'],
    createdAt: '2025-02-04T11:00:00Z',
  },
  {
    id: 'res-bee-practice-1',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-1',
    title: 'DC Network Circuit Theorems (Thevenin & Norton) Solved Practice Questions',
    type: 'practice_ques',
    filePath: '/sample-resources/bee_theorems_practice.pdf',
    fileName: 'BEE_Mod1_Theorems_Practice_Problems.pdf',
    fileSizeBytes: 1820000,
    fileMime: 'application/pdf',
    academicYear: '2025-2026',
    scheme: 'REV_2025',
    uploaderName: 'Department of Electrical Engineering',
    isVerified: true,
    downloadsCount: 2310,
    tags: ['Sem1', 'Practice Questions', 'Thevenin', 'Norton'],
    createdAt: '2025-02-05T09:00:00Z',
  },
  // --- YEAR-WISE SUBJECT PYQS (MID SEM & END SEM) ---
  {
    id: 'res-math1-pyq-endsem-24',
    subjectId: 'sub-math1',
    moduleId: undefined,
    title: 'Applied Mathematics – I End-Semester University Exam Question Paper (2024-25)',
    type: 'pyq',
    examType: 'end_sem',
    examYear: '2024-25',
    filePath: '/sample-resources/maths1_pyq_endsem_2024.pdf',
    fileName: 'AM1_EndSem_Question_Paper_2024_25.pdf',
    fileSizeBytes: 2100000,
    fileMime: 'application/pdf',
    academicYear: '2024-2025',
    scheme: 'REV_2025',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 4520,
    tags: ['PYQ', 'End Sem', '2024-25', 'Maths1', 'Official'],
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'res-math1-pyq-midsem-24',
    subjectId: 'sub-math1',
    moduleId: undefined,
    title: 'Applied Mathematics – I Mid-Semester Exam Question Paper (2024-25)',
    type: 'pyq',
    examType: 'mid_sem',
    examYear: '2024-25',
    filePath: '/sample-resources/maths1_pyq_midsem_2024.pdf',
    fileName: 'AM1_MidSem_Question_Paper_2024_25.pdf',
    fileSizeBytes: 1400000,
    fileMime: 'application/pdf',
    academicYear: '2024-2025',
    scheme: 'REV_2025',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 3890,
    tags: ['PYQ', 'Mid Sem', '2024-25', 'Maths1', 'Official'],
    createdAt: '2024-10-15T10:00:00Z',
  },
  {
    id: 'res-math1-pyq-endsem-23',
    subjectId: 'sub-math1',
    moduleId: undefined,
    title: 'Applied Mathematics – I End-Semester University Exam Question Paper (2023-24)',
    type: 'pyq',
    examType: 'end_sem',
    examYear: '2023-24',
    filePath: '/sample-resources/maths1_pyq_endsem_2023.pdf',
    fileName: 'AM1_EndSem_Question_Paper_2023_24.pdf',
    fileSizeBytes: 1980000,
    fileMime: 'application/pdf',
    academicYear: '2023-2024',
    scheme: 'REV_2024',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 3650,
    tags: ['PYQ', 'End Sem', '2023-24', 'Maths1', 'Official'],
    createdAt: '2024-01-12T10:00:00Z',
  },
  {
    id: 'res-phy-pyq-endsem-24',
    subjectId: 'sub-phy',
    moduleId: undefined,
    title: 'Engineering Physics End-Semester Exam Question Paper (2024-25)',
    type: 'pyq',
    examType: 'end_sem',
    examYear: '2024-25',
    filePath: '/sample-resources/physics_pyq_endsem_2024.pdf',
    fileName: 'Physics_EndSem_Question_Paper_2024_25.pdf',
    fileSizeBytes: 1850000,
    fileMime: 'application/pdf',
    academicYear: '2024-2025',
    scheme: 'REV_2025',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 3120,
    tags: ['PYQ', 'End Sem', '2024-25', 'Physics', '316U06C102'],
    createdAt: '2025-01-11T10:00:00Z',
  },
  {
    id: 'res-bee-pyq-endsem-24',
    subjectId: 'sub-bee',
    moduleId: undefined,
    title: 'Basic Electrical Engineering End-Semester Exam Question Paper (2024-25)',
    type: 'pyq',
    examType: 'end_sem',
    examYear: '2024-25',
    filePath: '/sample-resources/bee_pyq_endsem_2024.pdf',
    fileName: 'BEE_EndSem_Question_Paper_2024_25.pdf',
    fileSizeBytes: 2200000,
    fileMime: 'application/pdf',
    academicYear: '2024-2025',
    scheme: 'REV_2025',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 4210,
    tags: ['PYQ', 'End Sem', '2024-25', 'BEE', '316U06C104'],
    createdAt: '2025-01-12T10:00:00Z',
  },
  {
    id: 'res-spm-pyq-endsem-24',
    subjectId: 'sub-spm',
    moduleId: undefined,
    title: 'Structured Programming Methodology (C) End-Semester Exam Paper (2024-25)',
    type: 'pyq',
    examType: 'end_sem',
    examYear: '2024-25',
    filePath: '/sample-resources/spm_pyq_endsem_2024.pdf',
    fileName: 'SPM_EndSem_Question_Paper_2024_25.pdf',
    fileSizeBytes: 2450000,
    fileMime: 'application/pdf',
    academicYear: '2024-2025',
    scheme: 'REV_2025',
    uploaderName: 'Examination Cell',
    isVerified: true,
    downloadsCount: 3980,
    tags: ['PYQ', 'End Sem', '2024-25', 'SPM', '316U06C107'],
    createdAt: '2025-01-14T10:00:00Z',
  }
];

export const INITIAL_YOUTUBE_RESOURCES: YouTubeResource[] = [
  // --- Applied Mathematics – I (AM-1) User Curated Playlist Resources ---
  {
    id: 'yt-math1-mod1-matrices',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-1',
    title: 'Module 1: Matrices & System of Linear Equations',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLQ2Js_nO99cE&si=ZG3ReSPGqzrbhOyU',
    videoId: 'PLQ2Js_nO99cE',
    playlistId: 'PLQ2Js_nO99cE',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Comprehensive lecture series on Matrices, Rank of Matrix, and System of Linear Equations by Pradeep Giri.',
    tags: ['Maths1', 'Mod 1', 'Matrices', 'Pradeep Giri'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-06T10:00:00Z',
  },
  {
    id: 'yt-math1-mod2-partial-diff',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-2',
    title: 'Module 2: Partial Differentiation & Applications',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLL1NiXsy4ZgU&si=MWbMo9FPPWlgAVdd',
    videoId: 'PLL1NiXsy4ZgU',
    playlistId: 'PLL1NiXsy4ZgU',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Complete playlist on Partial Differentiation, Jacobians, and Maxima-Minima by Pradeep Giri.',
    tags: ['Maths1', 'Mod 2', 'Partial Diff', 'Pradeep Giri'],
    customThumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-08T12:00:00Z',
  },
  {
    id: 'yt-math1-mod3-homo-func',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-3',
    title: 'Module 3: Homogeneous Functions & Euler’s Theorem',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLYVfNY_bT6yY&si=4doJAzEiYHiLHmRF',
    videoId: 'PLYVfNY_bT6yY',
    playlistId: 'PLYVfNY_bT6yY',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Homogeneous functions, Euler’s theorem, and university derivations by Pradeep Giri.',
    tags: ['Maths1', 'Mod 3', 'Euler Theorem', 'Homogeneous Functions', 'Pradeep Giri'],
    customThumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-10T11:00:00Z',
  },
  {
    id: 'yt-math1-mod4-lde',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-4',
    title: 'Module 4: Linear Differential Equations (LDE)',
    channelName: 'Pradeep Giri Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLdXnNp9HebAo&si=O-pR4nvnJAf9e8NZ',
    videoId: 'PLdXnNp9HebAo',
    playlistId: 'PLdXnNp9HebAo',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Higher order Linear Differential Equations, Complementary Functions (CF), and Particular Integrals (PI) by Pradeep Giri.',
    tags: ['Maths1', 'Mod 4', 'LDE', 'Differential Equations', 'Pradeep Giri'],
    customThumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-12T09:00:00Z',
  },
  {
    id: 'yt-math1-mod5-complex',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-5',
    title: 'Module 5: Complex Numbers & Hyperbolic Functions',
    channelName: 'Saurabh Dahivadkar',
    youtubeUrl: 'https://youtube.com/playlist?list=PLKS7ZMKnbPrSsOQDQOpYrDUp-4zQO8YFX&si=EyY0uXHV8wx3rqfL',
    videoId: 'PLKS7ZMKnbPrSsOQDQOpYrDUp-4zQO8YFX',
    playlistId: 'PLKS7ZMKnbPrSsOQDQOpYrDUp-4zQO8YFX',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'De Moivre’s theorem, roots of complex numbers, circular and hyperbolic functions by Saurabh Dahivadkar.',
    tags: ['Maths1', 'Mod 5', 'Complex Numbers', 'Saurabh Dahivadkar'],
    customThumbnail: 'https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-14T10:00:00Z',
  },

  // --- Engineering Physics (Physics Jessy & Engineering Physics by Sanjiv Dual-Author Playlists) ---
  // Author 1: Physics Jessy
  {
    id: 'yt-phy-jessy-m1-interference',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-1',
    title: 'Module 1 (Part 1): Interference of Light - Physics Jessy',
    channelName: 'Physics Jessy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLm5sdXlz-wPmZa-W5Wku5ygnMi5psSN5s&si=tKmYP5q-Catm0Wa2',
    videoId: 'PLm5sdXlz-wPmZa-W5Wku5ygnMi5psSN5s',
    playlistId: 'PLm5sdXlz-wPmZa-W5Wku5ygnMi5psSN5s',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Thin film interference, wedge-shaped films, Newton’s rings, and anti-reflection coatings by Physics Jessy.',
    tags: ['Physics', 'Mod 1', 'Interference', 'Physics Jessy'],
    customThumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-15T11:00:00Z',
  },
  {
    id: 'yt-phy-jessy-m1-diffraction',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-1',
    title: 'Module 1 (Part 2): Diffraction of Light - Physics Jessy',
    channelName: 'Physics Jessy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLm5sdXlz-wPmF6vuhF_nXbRZ-JtozOiV3&si=_8cCu23bHbrQjEDX',
    videoId: 'PLm5sdXlz-wPmF6vuhF_nXbRZ-JtozOiV3',
    playlistId: 'PLm5sdXlz-wPmF6vuhF_nXbRZ-JtozOiV3',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Fraunhofer diffraction at single slit, double slit, and diffraction grating by Physics Jessy.',
    tags: ['Physics', 'Mod 1', 'Diffraction', 'Physics Jessy'],
    customThumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-15T12:00:00Z',
  },
  {
    id: 'yt-phy-jessy-m2-laser',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-2',
    title: 'Module 2 (Part 1): Lasers & Einstein Coefficients - Physics Jessy',
    channelName: 'Physics Jessy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLm5sdXlz-wPkAloYGB-rwfvjPqz5sr-Hk&si=qMP1NkRSF8U5isjU',
    videoId: 'PLm5sdXlz-wPkAloYGB-rwfvjPqz5sr-Hk',
    playlistId: 'PLm5sdXlz-wPkAloYGB-rwfvjPqz5sr-Hk',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Laser principles, population inversion, optical resonator, Nd:YAG, and He-Ne lasers by Physics Jessy.',
    tags: ['Physics', 'Mod 2', 'Laser', 'Physics Jessy'],
    customThumbnail: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-16T11:00:00Z',
  },
  {
    id: 'yt-phy-jessy-m2-fiber',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-2',
    title: 'Module 2 (Part 2): Optical Fiber & Numerical Aperture - Physics Jessy',
    channelName: 'Physics Jessy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLm5sdXlz-wPkJXmwlwWe5VwgzkZhjJV_1&si=TAwM3kXJAXN6ljmN',
    videoId: 'PLm5sdXlz-wPkJXmwlwWe5VwgzkZhjJV_1',
    playlistId: 'PLm5sdXlz-wPkJXmwlwWe5VwgzkZhjJV_1',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Optical fiber communication, numerical aperture, V-number, and attenuation by Physics Jessy.',
    tags: ['Physics', 'Mod 2', 'Optical Fiber', 'Physics Jessy'],
    customThumbnail: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-16T12:00:00Z',
  },
  {
    id: 'yt-phy-jessy-m3-quantum',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-3',
    title: 'Module 3: Quantum Mechanics & Schrödinger Equation - Physics Jessy',
    channelName: 'Physics Jessy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLm5sdXlz-wPnYiytC0i9XP2tu48lgrMiN&si=iBJMnSQEkBS2LeTl',
    videoId: 'PLm5sdXlz-wPnYiytC0i9XP2tu48lgrMiN',
    playlistId: 'PLm5sdXlz-wPnYiytC0i9XP2tu48lgrMiN',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'De Broglie hypothesis, phase and group velocities, and time-independent Schrödinger wave equation by Physics Jessy.',
    tags: ['Physics', 'Mod 3', 'Quantum Mechanics', 'Physics Jessy'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-17T11:00:00Z',
  },
  {
    id: 'yt-phy-jessy-m4-semi',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-4',
    title: 'Module 4 (Part 1): Semiconductor Physics & Fermi Level - Physics Jessy',
    channelName: 'Physics Jessy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLm5sdXlz-wPnadJGAui9KWK86cFLKNF0t&si=MNAYRk7mDx4GtKPb',
    videoId: 'PLm5sdXlz-wPnadJGAui9KWK86cFLKNF0t',
    playlistId: 'PLm5sdXlz-wPnadJGAui9KWK86cFLKNF0t',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Intrinsic/extrinsic semiconductors, Fermi-Dirac distribution, and Hall effect by Physics Jessy.',
    tags: ['Physics', 'Mod 4', 'Semiconductors', 'Physics Jessy'],
    customThumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-17T12:00:00Z',
  },
  {
    id: 'yt-phy-jessy-m4-electrodynamics',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-4',
    title: 'Module 4 (Part 2): Electrodynamics & Maxwell’s Equations - Physics Jessy',
    channelName: 'Physics Jessy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLm5sdXlz-wPnF73Q-AAnC8FtO92Jpc9JA&si=EA67b3yg-VKNzebt',
    videoId: 'PLm5sdXlz-wPnF73Q-AAnC8FtO92Jpc9JA',
    playlistId: 'PLm5sdXlz-wPnF73Q-AAnC8FtO92Jpc9JA',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Electrodynamics, displacement current, Maxwell’s equations, and electromagnetic wave propagation by Physics Jessy.',
    tags: ['Physics', 'Mod 4', 'Electrodynamics', 'Maxwell', 'Physics Jessy'],
    customThumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-17T13:00:00Z',
  },

  // Author 2: Engineering Physics by Sanjiv
  {
    id: 'yt-phy-sanjiv-m1-diffraction',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-1',
    title: 'Module 1 (Part 1): Diffraction of Light - Engineering Physics by Sanjiv',
    channelName: 'Engineering Physics by Sanjiv',
    youtubeUrl: 'https://youtube.com/playlist?list=PLQzUXa8lZVq_HKqpeG-UeZrFmDz1m0_SW&si=cG1pml1KNyLCKzf-',
    videoId: 'PLQzUXa8lZVq_HKqpeG-UeZrFmDz1m0_SW',
    playlistId: 'PLQzUXa8lZVq_HKqpeG-UeZrFmDz1m0_SW',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Diffraction at single slit, double slit, resolving power, and dispersive power by Dr. Sanjiv.',
    tags: ['Physics', 'Mod 1', 'Diffraction', 'Engineering Physics by Sanjiv'],
    customThumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-15T14:00:00Z',
  },
  {
    id: 'yt-phy-sanjiv-m1-interference',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-1',
    title: 'Module 1 (Part 2): Interference of Light - Engineering Physics by Sanjiv',
    channelName: 'Engineering Physics by Sanjiv',
    youtubeUrl: 'https://youtube.com/playlist?list=PLQzUXa8lZVq-tbELniG9R_NHKm7OQVUk9&si=VgOjceep4J5TF-V3',
    videoId: 'PLQzUXa8lZVq-tbELniG9R_NHKm7OQVUk9',
    playlistId: 'PLQzUXa8lZVq-tbELniG9R_NHKm7OQVUk9',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Thin film interference, conditions for maxima and minima, wedge shape films, and Newton’s rings by Dr. Sanjiv.',
    tags: ['Physics', 'Mod 1', 'Interference', 'Engineering Physics by Sanjiv'],
    customThumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-15T15:00:00Z',
  },
  {
    id: 'yt-phy-sanjiv-m2-laser',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-2',
    title: 'Module 2 (Part 1): Lasers & Applications - Engineering Physics by Sanjiv',
    channelName: 'Engineering Physics by Sanjiv',
    youtubeUrl: 'https://youtube.com/playlist?list=PLQzUXa8lZVq-tYb-kl0_1hU_ICJtXKj2J&si=x6S3vJ8un8PDEe_s',
    videoId: 'PLQzUXa8lZVq-tYb-kl0_1hU_ICJtXKj2J',
    playlistId: 'PLQzUXa8lZVq-tYb-kl0_1hU_ICJtXKj2J',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Properties of lasers, spontaneous & stimulated emission, population inversion, and semiconductor lasers by Dr. Sanjiv.',
    tags: ['Physics', 'Mod 2', 'Laser', 'Engineering Physics by Sanjiv'],
    customThumbnail: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-16T14:00:00Z',
  },
  {
    id: 'yt-phy-sanjiv-m2-fiber',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-2',
    title: 'Module 2 (Part 2): Optical Fiber Cable - Engineering Physics by Sanjiv',
    channelName: 'Engineering Physics by Sanjiv',
    youtubeUrl: 'https://youtube.com/playlist?list=PLQzUXa8lZVq8ej59AUl6bk78kMGVsT5nS&si=kXXh31QRU7aycaoZ',
    videoId: 'PLQzUXa8lZVq8ej59AUl6bk78kMGVsT5nS',
    playlistId: 'PLQzUXa8lZVq8ej59AUl6bk78kMGVsT5nS',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Optical fiber light propagation, acceptance angle, fractional index change, and fiber losses by Dr. Sanjiv.',
    tags: ['Physics', 'Mod 2', 'Optical Fiber', 'Engineering Physics by Sanjiv'],
    customThumbnail: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-16T15:00:00Z',
  },
  {
    id: 'yt-phy-sanjiv-m3-quantum',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-3',
    title: 'Module 3: Quantum Mechanics - Engineering Physics by Sanjiv',
    channelName: 'Engineering Physics by Sanjiv',
    youtubeUrl: 'https://youtube.com/playlist?list=PLQzUXa8lZVq8Zciw0MsOdPJ1t-bpPKV6_&si=sxowV_VwvhPP-ZgB',
    videoId: 'PLQzUXa8lZVq8Zciw0MsOdPJ1t-bpPKV6_',
    playlistId: 'PLQzUXa8lZVq8Zciw0MsOdPJ1t-bpPKV6_',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Quantum physics concepts, matter waves, uncertainty principle, and particle in a 1D box by Dr. Sanjiv.',
    tags: ['Physics', 'Mod 3', 'Quantum Mechanics', 'Engineering Physics by Sanjiv'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-17T14:00:00Z',
  },
  {
    id: 'yt-phy-sanjiv-m4-semi',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-4',
    title: 'Module 4 (Part 1): Semiconductor Physics - Engineering Physics by Sanjiv',
    channelName: 'Engineering Physics by Sanjiv',
    youtubeUrl: 'https://youtube.com/playlist?list=PLQzUXa8lZVq8lfZN5836sohUpRCt2b6oB&si=uLGns6Q_ppWDujv9',
    videoId: 'PLQzUXa8lZVq8lfZN5836sohUpRCt2b6oB',
    playlistId: 'PLQzUXa8lZVq8lfZN5836sohUpRCt2b6oB',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Energy band diagrams, direct/indirect band gap semiconductors, Fermi energy level, and Hall coefficient by Dr. Sanjiv.',
    tags: ['Physics', 'Mod 4', 'Semiconductors', 'Engineering Physics by Sanjiv'],
    customThumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-17T15:00:00Z',
  },
  {
    id: 'yt-phy-sanjiv-m4-electrodynamics',
    subjectId: 'sub-phy',
    moduleId: 'mod-phy-4',
    title: 'Module 4 (Part 2): Electrodynamics - Engineering Physics by Sanjiv',
    channelName: 'Engineering Physics by Sanjiv',
    youtubeUrl: 'https://youtube.com/playlist?list=PLQzUXa8lZVq97DPn9B7MlIm5CgTW6mMAc&si=vSlLZ4wSce1slZfo',
    videoId: 'PLQzUXa8lZVq97DPn9B7MlIm5CgTW6mMAc',
    playlistId: 'PLQzUXa8lZVq97DPn9B7MlIm5CgTW6mMAc',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Electrodynamics, Gauss law, Faraday law, Ampere-Maxwell law, and Poynting theorem by Dr. Sanjiv.',
    tags: ['Physics', 'Mod 4', 'Electrodynamics', 'Maxwell', 'Engineering Physics by Sanjiv'],
    customThumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-17T16:00:00Z',
  },

  // --- Engineering Chemistry ---
  {
    id: 'yt-chem-avani-m1',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-1',
    title: 'Module 1: Water Treatment & Hardness - Science by Avani',
    channelName: 'Science by Avani',
    youtubeUrl: 'https://youtube.com/playlist?list=PL2xHbdoT5bU8eQGswUpK8-223kHBuiCqz&si=5-qXIVwIlrqFbCk-',
    videoId: 'PL2xHbdoT5bU8eQGswUpK8-223kHBuiCqz',
    playlistId: 'PL2xHbdoT5bU8eQGswUpK8-223kHBuiCqz',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Types of hardness, EDTA determination, zeolite softening, BOD/COD calculations, and reverse osmosis by Science by Avani.',
    tags: ['Chemistry', '316U06C103', 'Water Treatment', 'Science by Avani'],
    customThumbnail: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T10:00:00Z',
  },
  {
    id: 'yt-chem-anjali-m2',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-2',
    title: 'Module 2: Green Chemistry - Chemistry by Dr. Anjali Saxena',
    channelName: 'Chemistry by Dr. Anjali Saxena',
    youtubeUrl: 'https://youtube.com/playlist?list=PLLf6O8XdGj03fkukqcW7HOTSK8u_up7nJ&si=t1rKVL-dCPZQ7v8M',
    videoId: 'PLLf6O8XdGj03fkukqcW7HOTSK8u_up7nJ',
    playlistId: 'PLLf6O8XdGj03fkukqcW7HOTSK8u_up7nJ',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Twelve principles of green chemistry, green metrics, atom economy, and sustainable reactions by Dr. Anjali Saxena.',
    tags: ['Chemistry', 'Mod 2', 'Green Chemistry', 'Chemistry by Dr. Anjali Saxena'],
    customThumbnail: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-19T10:00:00Z',
  },
  {
    id: 'yt-chem-mix-m3',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-3',
    title: 'Module 3: Engineering Chemistry Tutorials (Full Playlist)',
    channelName: 'Engineering Chemistry Tutorials',
    youtubeUrl: 'https://youtube.com/playlist?list=PLE-8tLvduWGQ9eV3LJ0E2EtzmXUJ7ZqBz&si=ECQVb8tOb4vpbmht',
    videoId: 'PLE-8tLvduWGQ9eV3LJ0E2EtzmXUJ7ZqBz',
    playlistId: 'PLE-8tLvduWGQ9eV3LJ0E2EtzmXUJ7ZqBz',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Comprehensive engineering chemistry video lectures and solved problems.',
    tags: ['Chemistry', 'Mod 3', 'Engineering Chemistry'],
    customThumbnail: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-19T11:00:00Z',
  },
  {
    id: 'yt-chem-anjali-m4-electrochem',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-4',
    title: 'Module 4 (Part 1): Electrochemistry - Chemistry by Dr. Anjali Saxena',
    channelName: 'Chemistry by Dr. Anjali Saxena',
    youtubeUrl: 'https://youtube.com/playlist?list=PLLf6O8XdGj03pNhe069q3fHouzq64Vvsm&si=HwEpVQm5voAVhvYK',
    videoId: 'PLLf6O8XdGj03pNhe069q3fHouzq64Vvsm',
    playlistId: 'PLLf6O8XdGj03pNhe069q3fHouzq64Vvsm',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Electrochemistry, Nernst equation, cell potentials, electrochemical cells, and battery systems by Dr. Anjali Saxena.',
    tags: ['Chemistry', 'Mod 4', 'Electrochemistry', 'Chemistry by Dr. Anjali Saxena'],
    customThumbnail: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-19T12:00:00Z',
  },
  {
    id: 'yt-chem-anjali-m4-corrosion',
    subjectId: 'sub-chem',
    moduleId: 'mod-ch-4',
    title: 'Module 4 (Part 2): Corrosion Science - Chemistry by Dr. Anjali Saxena',
    channelName: 'Chemistry by Dr. Anjali Saxena',
    youtubeUrl: 'https://youtube.com/playlist?list=PLLf6O8XdGj00lVydanLfC6bcT4aXGJN4V&si=ffsTRur_-oJ9llk6',
    videoId: 'PLLf6O8XdGj00lVydanLfC6bcT4aXGJN4V',
    playlistId: 'PLLf6O8XdGj00lVydanLfC6bcT4aXGJN4V',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Corrosion mechanisms, dry and wet corrosion, galvanic corrosion, cathodic protection, and coatings by Dr. Anjali Saxena.',
    tags: ['Chemistry', 'Mod 4', 'Corrosion', 'Chemistry by Dr. Anjali Saxena'],
    customThumbnail: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-19T12:30:00Z',
  },

  // --- Basic Electrical Engineering ---
  {
    id: 'yt-bee-master',
    subjectId: 'sub-bee',
    moduleId: undefined,
    title: 'Basic Electrical Engineering: Complete Syllabus Master Playlist',
    channelName: 'Last Moment Tuitions',
    youtubeUrl: 'https://youtube.com/playlist?list=PL9RcWoqXmzaLTYUdnzKhF4bYug3GjGcEc&si=jLKodK1Cw_tJADMt',
    videoId: 'PL9RcWoqXmzaLTYUdnzKhF4bYug3GjGcEc',
    playlistId: 'PL9RcWoqXmzaLTYUdnzKhF4bYug3GjGcEc',
    isPlaylist: true,
    duration: 'Full Syllabus',
    description: 'Complete Basic Electrical Engineering syllabus master series covering DC Circuits, AC Fundamentals, 3-Phase Systems, and Transformers.',
    tags: ['Master Playlist', 'BEE', '316U06C104', 'Full Course'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-08T10:00:00Z',
  },
  {
    id: 'yt-bee-pce-m1',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-1',
    title: 'Module 1: DC Circuits & Network Theorems - Perfect Computer Engineer',
    channelName: 'Perfect Computer Engineer',
    youtubeUrl: 'https://youtube.com/playlist?list=PLPIwNooIb9vjC5Hz7xIUXJw54LkB2MG2i&si=ONirEgZpnE8pAGQ2',
    videoId: 'PLPIwNooIb9vjC5Hz7xIUXJw54LkB2MG2i',
    playlistId: 'PLPIwNooIb9vjC5Hz7xIUXJw54LkB2MG2i',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Kirchhoff’s laws, Mesh & Nodal analysis, Thevenin, Norton, Superposition & Maximum Power Transfer theorems by Perfect Computer Engineer.',
    tags: ['BEE', 'Mod 1', 'DC Circuits', 'Theorems', 'Perfect Computer Engineer'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T09:00:00Z',
  },
  {
    id: 'yt-bee-pce-m2',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-2',
    title: 'Module 2: AC Circuits (Single Phase) - Perfect Computer Engineer',
    channelName: 'Perfect Computer Engineer',
    youtubeUrl: 'https://youtube.com/playlist?list=PLPIwNooIb9vgYjKb1N14ITkmhX2oNrNi3&si=sOtE-MRfEcECn-pB',
    videoId: 'PLPIwNooIb9vgYjKb1N14ITkmhX2oNrNi3',
    playlistId: 'PLPIwNooIb9vgYjKb1N14ITkmhX2oNrNi3',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'AC Fundamentals, RMS/Average values, Phasor diagrams, and R-L-C Series/Parallel Resonance by Perfect Computer Engineer.',
    tags: ['BEE', 'Mod 2', 'AC Circuits', 'Perfect Computer Engineer'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T10:00:00Z',
  },
  {
    id: 'yt-bee-ekeeda-m2',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-2',
    title: 'Module 2: AC Circuits (Full Course) - Ekeeda',
    channelName: 'Ekeeda',
    youtubeUrl: 'https://youtube.com/playlist?list=PL4K9r9dYCOorFJYvPZ3VBLDJVpWA5p481&si=jzOD6yA6KxHMEbbe',
    videoId: 'PL4K9r9dYCOorFJYvPZ3VBLDJVpWA5p481',
    playlistId: 'PL4K9r9dYCOorFJYvPZ3VBLDJVpWA5p481',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Detailed single-phase AC circuit analysis, impedances, power factor, and resonance derivations by Ekeeda.',
    tags: ['BEE', 'Mod 2', 'AC Circuits', 'Ekeeda'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T10:15:00Z',
  },
  {
    id: 'yt-bee-saurabh-m2',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-2',
    title: 'Module 2: AC Fundamentals & Resonance - Saurabh Dahivadkar',
    channelName: 'Saurabh Dahivadkar',
    youtubeUrl: 'https://youtube.com/playlist?list=PLKS7ZMKnbPrQZP4zxS47bzkf8sGYlaIKM&si=UOBk3HHNQ4uu-b2e',
    videoId: 'PLKS7ZMKnbPrQZP4zxS47bzkf8sGYlaIKM',
    playlistId: 'PLKS7ZMKnbPrQZP4zxS47bzkf8sGYlaIKM',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'AC quantities, sinusoidal waveforms, phasor representation, and series-parallel RLC resonance by Saurabh Dahivadkar.',
    tags: ['BEE', 'Mod 2', 'AC Fundamentals', 'Saurabh Dahivadkar'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T10:30:00Z',
  },
  {
    id: 'yt-bee-saurabh-m3',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-3',
    title: 'Module 3: Three Phase AC Circuits - Saurabh Dahivadkar',
    channelName: 'Saurabh Dahivadkar',
    youtubeUrl: 'https://youtube.com/playlist?list=PLKS7ZMKnbPrSS6_Mk0UbOySQzDBY-uHJQ&si=kJlmzuqGUhfI-vf2',
    videoId: 'PLKS7ZMKnbPrSS6_Mk0UbOySQzDBY-uHJQ',
    playlistId: 'PLKS7ZMKnbPrSS6_Mk0UbOySQzDBY-uHJQ',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Balanced Star and Delta 3-Phase systems, Line vs Phase voltages/currents, and Two-Wattmeter power measurement by Saurabh Dahivadkar.',
    tags: ['BEE', 'Mod 3', 'Three Phase', 'Star Delta', 'Saurabh Dahivadkar'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T11:00:00Z',
  },
  {
    id: 'yt-bee-ekeeda-m3',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-3',
    title: 'Module 3: Three Phase AC Systems - Ekeeda',
    channelName: 'Ekeeda',
    youtubeUrl: 'https://youtube.com/playlist?list=PL4K9r9dYCOooO5s49HTN7Tavmg5q_Ufqn&si=9LC-HNMVs5wzUeoy',
    videoId: 'PL4K9r9dYCOooO5s49HTN7Tavmg5q_Ufqn',
    playlistId: 'PL4K9r9dYCOooO5s49HTN7Tavmg5q_Ufqn',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: '3-Phase star and delta configurations, phasor diagrams, power & power factor calculations by Ekeeda.',
    tags: ['BEE', 'Mod 3', 'Three Phase', 'Ekeeda'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T11:30:00Z',
  },
  {
    id: 'yt-bee-ekeeda-m4-transformers',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-4',
    title: 'Module 4 (Part 1): Single Phase Transformers - Ekeeda',
    channelName: 'Ekeeda',
    youtubeUrl: 'https://youtube.com/playlist?list=PL4K9r9dYCOors6MRFwoIe9_iBzSzUp2Zi&si=aOD_gO13eU-Kion9',
    videoId: 'PL4K9r9dYCOors6MRFwoIe9_iBzSzUp2Zi',
    playlistId: 'PL4K9r9dYCOors6MRFwoIe9_iBzSzUp2Zi',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Working principle, construction, EMF equation, transformation ratio, losses, and efficiency of Single-Phase Transformers by Ekeeda.',
    tags: ['BEE', 'Mod 4', 'Transformers', 'Ekeeda'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T12:00:00Z',
  },
  {
    id: 'yt-bee-ekeeda-m4-machines',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-4',
    title: 'Module 4 (Part 2): Electrical Machines & Induction Motors - Ekeeda',
    channelName: 'Ekeeda',
    youtubeUrl: 'https://youtube.com/playlist?list=PL4K9r9dYCOooB-nXHA6uOBmaWMDYrhhLM&si=AKN0W2oKTUN31AK4',
    videoId: 'PL4K9r9dYCOooB-nXHA6uOBmaWMDYrhhLM',
    playlistId: 'PL4K9r9dYCOooB-nXHA6uOBmaWMDYrhhLM',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Rotating magnetic field principle, construction, torque-slip characteristics, and working of 3-Phase Induction Motors by Ekeeda.',
    tags: ['BEE', 'Mod 4', 'Induction Motors', 'Machines', 'Ekeeda'],
    customThumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-18T12:30:00Z',
  },

  // --- Engineering Drawing ---
  {
    id: 'yt-ed-master-autocad',
    subjectId: 'sub-ed',
    moduleId: undefined,
    title: 'Engineering Drawing & AutoCAD: Complete Full Course - Parag Sarode',
    channelName: 'Parag Sarode',
    youtubeUrl: 'https://youtube.com/playlist?list=PLMAIn9IBcz0E&si=8JHUYCBnQH_W6kVr',
    videoId: 'PLMAIn9IBcz0E',
    playlistId: 'PLMAIn9IBcz0E',
    isPlaylist: true,
    duration: 'Full Course',
    description: 'Complete Engineering Drawing, 2D/3D drafting commands, and AutoCAD masterclass by Parag Sarode.',
    tags: ['Master Playlist', 'Engineering Drawing', 'AutoCAD', '316U06C105', 'Parag Sarode'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 'yt-ed-tikle-m1',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-1',
    title: 'Module 1: Orthographic Projections & Sectional Views - Tikle\'s Academy',
    channelName: 'Tikle\'s Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLDN15nk5uLiBpnIOK5r3KXdfFOVzGHJSt&si=RwRN9EflwUAr0Pt7',
    videoId: 'PLDN15nk5uLiBpnIOK5r3KXdfFOVzGHJSt',
    playlistId: 'PLDN15nk5uLiBpnIOK5r3KXdfFOVzGHJSt',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'First angle and third angle orthographic projection methods, front view, top view, side view, and full sectional views by Tikle\'s Academy.',
    tags: ['Engineering Drawing', 'Mod 1', 'Orthographic', 'Tikle\'s Academy'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T14:30:00Z',
  },
  {
    id: 'yt-ed-tikle-m2-lines',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-2',
    title: 'Module 2 (Part 1): Projections of Straight Lines - Tikle\'s Academy',
    channelName: 'Tikle\'s Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLDN15nk5uLiC9wFOTiDp8ekWAf40BwSct&si=Um3PX5FKCcGvNgYv',
    videoId: 'PLDN15nk5uLiC9wFOTiDp8ekWAf40BwSct',
    playlistId: 'PLDN15nk5uLiC9wFOTiDp8ekWAf40BwSct',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Lines inclined to HP and VP, true length determinations, traces, and apparent angles by Tikle\'s Academy.',
    tags: ['Engineering Drawing', 'Mod 2', 'Lines', 'Tikle\'s Academy'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T15:00:00Z',
  },
  {
    id: 'yt-ed-tikle-m2-planes',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-2',
    title: 'Module 2 (Part 2): Projections of Planes - Tikle\'s Academy',
    channelName: 'Tikle\'s Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLDN15nk5uLiBVR22X01vcnvVCuQIklXGx&si=cNFbH398QwhIhnBF',
    videoId: 'PLDN15nk5uLiBVR22X01vcnvVCuQIklXGx',
    playlistId: 'PLDN15nk5uLiBVR22X01vcnvVCuQIklXGx',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Projections of regular geometric planes (triangular, square, hexagonal, circular) inclined to reference planes by Tikle\'s Academy.',
    tags: ['Engineering Drawing', 'Mod 2', 'Planes', 'Tikle\'s Academy'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T15:15:00Z',
  },
  {
    id: 'yt-ed-tikle-m3',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-3',
    title: 'Module 3: Projections of Solids - Tikle\'s Academy',
    channelName: 'Tikle\'s Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLDN15nk5uLiA9qy-OWuoEYoXsu7lsSaE9&si=HjUWflNeAWl7Z2Uw',
    videoId: 'PLDN15nk5uLiA9qy-OWuoEYoXsu7lsSaE9',
    playlistId: 'PLDN15nk5uLiA9qy-OWuoEYoXsu7lsSaE9',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Projections of regular prisms, pyramids, cylinders, and cones with axis inclined to reference planes by Tikle\'s Academy.',
    tags: ['Engineering Drawing', 'Mod 3', 'Solids', 'Tikle\'s Academy'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T15:30:00Z',
  },
  {
    id: 'yt-ed-tikle-m4',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-4',
    title: 'Module 4: Sections & Lateral Development of Solids - Tikle\'s Academy',
    channelName: 'Tikle\'s Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLDN15nk5uLiCxbMOdIIVDZ4i1IslzrT1W&si=DqvKa8KrKhi0ZBdm',
    videoId: 'PLDN15nk5uLiCxbMOdIIVDZ4i1IslzrT1W',
    playlistId: 'PLDN15nk5uLiCxbMOdIIVDZ4i1IslzrT1W',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Sections of solids, cutting planes, and lateral surface development of truncated prisms, pyramids, and cylinders by Tikle\'s Academy.',
    tags: ['Engineering Drawing', 'Mod 4', 'Sections', 'Development', 'Tikle\'s Academy'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T16:00:00Z',
  },
  {
    id: 'yt-ed-tikle-m5',
    subjectId: 'sub-ed',
    moduleId: 'mod-ed-5',
    title: 'Module 5: Isometric Projections & Views - Tikle\'s Academy',
    channelName: 'Tikle\'s Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLDN15nk5uLiBrAkdOhEvkmVPs2UtwfGao&si=4w1w9DycP7T85bXP',
    videoId: 'PLDN15nk5uLiBrAkdOhEvkmVPs2UtwfGao',
    playlistId: 'PLDN15nk5uLiBrAkdOhEvkmVPs2UtwfGao',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Isometric scale construction, isometric views vs projections of machine components and composite solids by Tikle\'s Academy.',
    tags: ['Engineering Drawing', 'Mod 5', 'Isometric', 'Tikle\'s Academy'],
    customThumbnail: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-20T16:30:00Z',
  },

  // --- Structured Programming Methodology (C/C++) ---
  {
    id: 'yt-spm-ab-initio',
    subjectId: 'sub-spm',
    moduleId: undefined,
    title: 'C++ & Programming OST: Complete Master Course - Ab Initio (Kaustubh Sir)',
    channelName: 'Ab Initio (Kaustubh Sir)',
    youtubeUrl: 'https://youtube.com/playlist?list=PLILyE8uN3CXMm2XkwNPKu3Y7qBSipP1R9&si=5oJ-9NrerRHEvbhI',
    videoId: 'PLILyE8uN3CXMm2XkwNPKu3Y7qBSipP1R9',
    playlistId: 'PLILyE8uN3CXMm2XkwNPKu3Y7qBSipP1R9',
    isPlaylist: true,
    duration: 'Full Course',
    description: 'Complete programming and software technologies masterclass covering algorithms, syntax, control structures, pointers, and memory by Kaustubh Sir.',
    tags: ['Master Playlist', 'SPM', '316U06C107', 'C/C++', 'Kaustubh Sir'],
    customThumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-25T14:00:00Z',
  },
  {
    id: 'yt-spm-cwh-full',
    subjectId: 'sub-spm',
    moduleId: 'mod-spm-1',
    title: 'Programming Tutorials in Hindi: Full Course - CodeWithHarry',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://youtube.com/playlist?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&si=hczkeMUtEYycxhAW',
    videoId: 'PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL',
    playlistId: 'PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Comprehensive step-by-step programming tutorial series covering variables, branching, loops, arrays, pointers, and functions in Hindi by CodeWithHarry.',
    tags: ['SPM', 'Mod 1', 'CodeWithHarry', 'Hindi Tutorials'],
    customThumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-25T14:30:00Z',
  },
  {
    id: 'yt-spm-coderarmy',
    subjectId: 'sub-spm',
    moduleId: 'mod-spm-1',
    title: 'Complete Programming Playlist: Basics to Advanced - Coder Army',
    channelName: 'Coder Army',
    youtubeUrl: 'https://youtube.com/playlist?list=PLQEaRBV9gAFsdNoZYUcVG6ygpwd0lUrIH&si=C-d85jKjoIZCbQ-a',
    videoId: 'PLQEaRBV9gAFsdNoZYUcVG6ygpwd0lUrIH',
    playlistId: 'PLQEaRBV9gAFsdNoZYUcVG6ygpwd0lUrIH',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Master programming playlist covering logic building, arrays, matrices, string handling, functions, recursion, and pointers by Coder Army.',
    tags: ['SPM', 'Mod 1', 'Coder Army', 'Master Course'],
    customThumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-01-25T15:00:00Z',
  },

  // --- Semester 2 Courses ---
  // --- Applied Mathematics – II (316U06C201) ---
  {
    id: 'yt-math2-m1-pradeep',
    subjectId: 'sub-math2',
    moduleId: 'mod-m2-1',
    title: 'Module 1: Eigenvalues and Eigenvectors (Full Playlist) - Pradeep Giri',
    channelName: 'Pradeep Giri',
    youtubeUrl: 'https://youtube.com/playlist?list=PLVloHBWdUExc&si=YsRnVx8pLTscZ7fK',
    videoId: 'PLVloHBWdUExc',
    playlistId: 'PLVloHBWdUExc',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Characteristic equation, Cayley-Hamilton theorem, eigenvalues, eigenvectors, similarity, and diagonalization of matrices by Pradeep Giri.',
    tags: ['Maths2', '316U06C201', 'Mod 1', 'Eigenvalues', 'Pradeep Giri'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'yt-math2-m2-pradeep',
    subjectId: 'sub-math2',
    moduleId: 'mod-m2-2',
    title: 'Module 2: Successive Differentiation & Expansion of Functions (Full Playlist) - Pradeep Giri',
    channelName: 'Pradeep Giri',
    youtubeUrl: 'https://youtube.com/playlist?list=PLGZl4p6vpALc&si=F_rPd3vuYn_C5jTF',
    videoId: 'PLGZl4p6vpALc',
    playlistId: 'PLGZl4p6vpALc',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'nth derivative of standard functions, Leibnitz’s theorem, Taylor’s and Maclaurin’s series expansions by Pradeep Giri.',
    tags: ['Maths2', '316U06C201', 'Mod 2', 'Leibnitz', 'Expansion', 'Pradeep Giri'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-01T11:00:00Z',
  },
  {
    id: 'yt-math2-m3-pradeep',
    subjectId: 'sub-math2',
    moduleId: 'mod-m2-3',
    title: 'Module 3: Beta & Gamma Functions & DUIS (Full Playlist) - Pradeep Giri',
    channelName: 'Pradeep Giri',
    youtubeUrl: 'https://youtube.com/playlist?list=PLZlV12KqUIyc&si=1iC-E89f0vgQOrLb',
    videoId: 'PLZlV12KqUIyc',
    playlistId: 'PLZlV12KqUIyc',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Beta and Gamma function properties, and Differentiation Under Integral Sign (DUIS) with constant/variable limits by Pradeep Giri.',
    tags: ['Maths2', '316U06C201', 'Mod 3', 'Beta Gamma', 'DUIS', 'Pradeep Giri'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-01T12:00:00Z',
  },
  {
    id: 'yt-math2-m4-mathmagix',
    subjectId: 'sub-math2',
    moduleId: 'mod-m2-4',
    title: 'Module 4: Rectification of Plane Curves (Full Playlist) - MathMagix',
    channelName: 'MathMagix',
    youtubeUrl: 'https://youtube.com/playlist?list=PLMoHHTLiAvKU&si=JRPfBkWwFCogLHYR',
    videoId: 'PLMoHHTLiAvKU',
    playlistId: 'PLMoHHTLiAvKU',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Rectification of plane curves in Cartesian, parametric, and polar coordinates by MathMagix.',
    tags: ['Maths2', '316U06C201', 'Mod 4', 'Rectification', 'MathMagix'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-01T13:00:00Z',
  },
  {
    id: 'yt-math2-m5-mix',
    subjectId: 'sub-math2',
    moduleId: 'mod-m2-5',
    title: 'Module 5: Multiple Integration & Applications (Full Playlist)',
    channelName: 'Multiple Authors (Curated)',
    youtubeUrl: 'https://youtube.com/playlist?list=PLD0wrDr01Qiw&si=toiT0vHVdDt490mu',
    videoId: 'PLD0wrDr01Qiw',
    playlistId: 'PLD0wrDr01Qiw',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Double integrals, change of order, polar coordinates, triple integration in Cartesian, cylindrical, and spherical coordinates, area & volume.',
    tags: ['Maths2', '316U06C201', 'Mod 5', 'Multiple Integration', 'Double Integrals', 'Triple Integrals'],
    customThumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-01T14:00:00Z',
  },
  {
    id: 'yt-oop-ab-initio',
    subjectId: 'sub-oop',
    moduleId: undefined,
    title: 'C++ OST: Complete Object Oriented Programming - Ab Initio (Kaustubh Sir)',
    channelName: 'Ab Initio (Kaustubh Sir)',
    youtubeUrl: 'https://youtube.com/playlist?list=PLILyE8uN3CXMm2XkwNPKu3Y7qBSipP1R9&si=5oJ-9NrerRHEvbhI',
    videoId: 'PLILyE8uN3CXMm2XkwNPKu3Y7qBSipP1R9',
    playlistId: 'PLILyE8uN3CXMm2XkwNPKu3Y7qBSipP1R9',
    isPlaylist: true,
    duration: 'Full Course',
    description: 'Complete C++ and Object-Oriented Software Technologies course covering OOP concepts, classes, inheritance, polymorphism, and STL by Kaustubh Sir.',
    tags: ['Master Playlist', 'OOP', '316U06C205', 'C++', 'OST', 'Kaustubh Sir'],
    customThumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-05T10:00:00Z',
  },
  {
    id: 'yt-oop-cwh-full',
    subjectId: 'sub-oop',
    moduleId: 'mod-oop-1',
    title: 'C++ Tutorials in Hindi: Full Course - CodeWithHarry',
    channelName: 'CodeWithHarry',
    youtubeUrl: 'https://youtube.com/playlist?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&si=hczkeMUtEYycxhAW',
    videoId: 'PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL',
    playlistId: 'PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'Complete C++ tutorial series covering syntax, OOP, constructors, friend functions, templates, and STL in Hindi by CodeWithHarry.',
    tags: ['OOP', 'C++', 'CodeWithHarry', 'Hindi Tutorials'],
    customThumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-05T10:30:00Z',
  },
  {
    id: 'yt-oop-coderarmy',
    subjectId: 'sub-oop',
    moduleId: 'mod-oop-1',
    title: 'C++ Complete Playlist: Fundamentals to Advanced - Coder Army',
    channelName: 'Coder Army',
    youtubeUrl: 'https://youtube.com/playlist?list=PLQEaRBV9gAFsdNoZYUcVG6ygpwd0lUrIH&si=C-d85jKjoIZCbQ-a',
    videoId: 'PLQEaRBV9gAFsdNoZYUcVG6ygpwd0lUrIH',
    playlistId: 'PLQEaRBV9gAFsdNoZYUcVG6ygpwd0lUrIH',
    isPlaylist: true,
    duration: 'Full Playlist',
    description: 'In-depth C++ mastercourse with data structures, algorithms, object-oriented design, and advanced STL by Coder Army.',
    tags: ['OOP', 'C++', 'Coder Army', 'Master Course'],
    customThumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-05T11:00:00Z',
  },

  // --- Digital Logic Design (316U06C203) ---
  {
    id: 'yt-dld-sudhakar',
    subjectId: 'sub-dld',
    moduleId: undefined,
    title: 'Digital Logic Design: Complete Full Course - Sudhakar Atchala',
    channelName: 'Sudhakar Atchala',
    youtubeUrl: 'https://youtube.com/playlist?list=PLXj4XH7LcRfBQXAd8FPZXmMzxZY-rViLP&si=tdTTFU6BtL4vIDad',
    videoId: 'PLXj4XH7LcRfBQXAd8FPZXmMzxZY-rViLP',
    playlistId: 'PLXj4XH7LcRfBQXAd8FPZXmMzxZY-rViLP',
    isPlaylist: true,
    duration: 'Full Course',
    description: 'Complete Digital Logic Design masterclass covering Number Systems, Boolean Algebra, K-Maps, Combinational Circuits, Flip-Flops, Registers, Counters, and Finite State Machines by Sudhakar Atchala.',
    tags: ['Master Playlist', 'DLD', '316U06C203', 'Sudhakar Atchala', 'Digital Logic'],
    customThumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-06T10:00:00Z',
  },
  {
    id: 'yt-dld-neso',
    subjectId: 'sub-dld',
    moduleId: undefined,
    title: 'Digital Electronics & Logic Design (Full Playlist) - Neso Academy',
    channelName: 'Neso Academy',
    youtubeUrl: 'https://youtube.com/playlist?list=PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm&si=29-KAx_-9bePTkuA',
    videoId: 'PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm',
    playlistId: 'PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm',
    isPlaylist: true,
    duration: 'Full Course',
    description: 'Legendary complete course on Digital Electronics and Logic Design covering gates, boolean algebra, minimization, combinational and sequential circuit design by Neso Academy.',
    tags: ['Master Playlist', 'DLD', '316U06C203', 'Neso Academy', 'Digital Electronics'],
    customThumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-06T10:30:00Z',
  },
  {
    id: 'yt-dld-aae',
    subjectId: 'sub-dld',
    moduleId: undefined,
    title: 'Digital Electronics (Complete Master Series) - All About Electronics',
    channelName: 'All About Electronics',
    youtubeUrl: 'https://youtube.com/playlist?list=PLwjK_iyK4LLBC_so3odA64E2MLgIRKafl&si=cTbrzA9TYRr3lRC- ',
    videoId: 'PLwjK_iyK4LLBC_so3odA64E2MLgIRKafl',
    playlistId: 'PLwjK_iyK4LLBC_so3odA64E2MLgIRKafl',
    isPlaylist: true,
    duration: 'Full Course',
    description: 'In-depth animations and crystal-clear explanations of Digital Logic, K-Maps, Adders/Subtractors, Sequential circuits, Flip-Flops, and Counters by All About Electronics.',
    tags: ['Master Playlist', 'DLD', '316U06C203', 'All About Electronics', 'Digital Logic'],
    customThumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    createdAt: '2025-02-06T11:00:00Z',
  },
];

export const INITIAL_FLASHCARD_DECKS: FlashcardDeck[] = [
  {
    id: 'deck-math1-core',
    subjectId: 'sub-math1',
    moduleId: 'mod-m1-5',
    title: 'Applied Mathematics – I: High-Yield Formulas',
    description: 'Essential De Moivre formulas, Euler homogeneous theorems, and rank reduction rules.',
    createdAt: '2025-01-15T00:00:00Z',
    cards: [
      {
        id: 'card-m1',
        deckId: 'deck-math1-core',
        front: 'State De Moivre’s Theorem for integer indices n.',
        back: 'For any real number θ and integer n:\n(cos θ + i sin θ)^n = cos(nθ) + i sin(nθ).',
        tags: ['Maths1', 'DeMoivre', 'Formulas'],
        difficulty: 'easy',
      },
      {
        id: 'card-m2',
        deckId: 'deck-math1-core',
        front: 'State Euler’s Theorem for a homogeneous function u = f(x, y) of degree n.',
        back: 'x(∂u/∂x) + y(∂u/∂y) = n · u\nand\nx²(∂²u/∂x²) + 2xy(∂²u/∂x∂y) + y²(∂²u/∂y²) = n(n - 1) · u.',
        tags: ['Maths1', 'Euler', 'PartialDiff'],
        difficulty: 'medium',
      },
      {
        id: 'card-m3',
        deckId: 'deck-math1-core',
        front: 'When is a square matrix A considered Unitary?',
        back: 'A matrix A is unitary if (A^θ) · A = A · (A^θ) = I, where A^θ is the conjugate transpose of A.',
        tags: ['Maths1', 'Matrices', 'Unitary'],
        difficulty: 'medium',
      }
    ]
  },
  {
    id: 'deck-bee-core',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-1',
    title: 'Basic Electrical Engineering: Network Theorems',
    description: 'Thevenin, Norton, and Maximum Power Transfer conditions for circuit analysis.',
    createdAt: '2025-01-20T00:00:00Z',
    cards: [
      {
        id: 'card-b1',
        deckId: 'deck-bee-core',
        front: 'State Maximum Power Transfer Theorem for DC resistive networks.',
        back: 'Maximum power is transferred from a source to a load resistance when RL = Rth (load resistance equals Thevenin equivalent resistance). Under this condition, Pmax = (Vth²)/(4 · Rth).',
        tags: ['BEE', 'MaxPower', 'Theorems'],
        difficulty: 'easy',
      },
      {
        id: 'card-b2',
        deckId: 'deck-bee-core',
        front: 'What is the relationship between Thevenin voltage (Vth), Norton current (IN), and equivalent resistance (Rth)?',
        back: 'Vth = IN · Rth   or   IN = Vth / Rth, where Rth is identical in both models.',
        tags: ['BEE', 'Thevenin', 'Norton'],
        difficulty: 'easy',
      }
    ]
  }
];

export const INITIAL_DIAGRAMS: MermaidDiagram[] = [
  {
    id: 'diag-bee-theorems',
    subjectId: 'sub-bee',
    moduleId: 'mod-bee-1',
    title: 'DC Network Theorem Decision Flowchart',
    diagramType: 'flowchart',
    explanation: 'Step-by-step decision tree for applying Thevenin, Norton, or Superposition theorems to solve circuit questions.',
    mermaidCode: `graph TD
    Start([Given DC Circuit]) --> CheckSources{Multiple Independent Sources?}
    CheckSources -->|Yes & Single Linear Response Needed| Super[Apply Superposition Theorem: Activate 1 Source at a time]
    CheckSources -->|Variable Load Resistor RL Present| ThevDec{Analyze via Thevenin or Norton?}
    
    ThevDec -->|Voltage Source Model| Thevenin[1. Remove RL and find Open Circuit Vth\\n2. Deactivate Sources to find Rth\\n3. IL = Vth / Rth + RL]
    ThevDec -->|Current Source Model| Norton[1. Short Terminals A-B to find IN\\n2. Find Norton Resistance RN = Rth\\n3. IL = IN * RN / RN + RL]
    
    Thevenin --> PowerCheck{Max Power Required?}
    Norton --> PowerCheck
    PowerCheck -->|RL = Rth| MaxP[Pmax = Vth^2 / 4Rth]
    PowerCheck -->|Standard Load| Done([Calculate Load Voltage & Current])`,
    createdAt: '2025-01-20T00:00:00Z',
  }
];
